// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_query.sql

package db

import (
	"context"
)

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    published_at
FROM articles
WHERE slug = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.PublishedAt,
	)
	return i, err
}

const getArticles = `-- name: GetArticles :many
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    published_at
FROM articles
ORDER BY featured DESC, published_at DESC
LIMIT $1 OFFSET $2
`

type GetArticlesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetArticles(ctx context.Context, arg GetArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, getArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.CoverUrl,
			&i.Alt,
			&i.Author,
			&i.Featured,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
