// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    published_at
FROM articles
WHERE slug = $1
`

type GetArticleBySlugRow struct {
	ID          pgtype.UUID
	Slug        string
	Title       string
	Excerpt     string
	Content     string
	CoverUrl    string
	Alt         pgtype.Text
	Author      pgtype.Text
	Featured    bool
	PublishedAt pgtype.Timestamp
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.PublishedAt,
	)
	return i, err
}

const getArticles = `-- name: GetArticles :many
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    published_at
FROM articles
ORDER BY featured DESC, published_at DESC
LIMIT $2 OFFSET $1
`

type GetArticlesParams struct {
	OffsetCount int32
	LimitCount  int32
}

type GetArticlesRow struct {
	ID          pgtype.UUID
	Slug        string
	Title       string
	Excerpt     string
	Content     string
	CoverUrl    string
	Alt         pgtype.Text
	Author      pgtype.Text
	Featured    bool
	PublishedAt pgtype.Timestamp
}

func (q *Queries) GetArticles(ctx context.Context, arg GetArticlesParams) ([]GetArticlesRow, error) {
	rows, err := q.db.Query(ctx, getArticles, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesRow{}
	for rows.Next() {
		var i GetArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.CoverUrl,
			&i.Alt,
			&i.Author,
			&i.Featured,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
