// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    blocks
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    created_at,
    blocks
`

type CreateArticleParams struct {
	Slug     string
	Title    string
	Excerpt  string
	Content  string
	CoverUrl string
	Alt      pgtype.Text
	Author   pgtype.Text
	Featured bool
	Blocks   []byte
}

type CreateArticleRow struct {
	ID        pgtype.UUID
	Slug      string
	Title     string
	Excerpt   string
	Content   string
	CoverUrl  string
	Alt       pgtype.Text
	Author    pgtype.Text
	Featured  bool
	CreatedAt pgtype.Timestamp
	Blocks    []byte
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Content,
		arg.CoverUrl,
		arg.Alt,
		arg.Author,
		arg.Featured,
		arg.Blocks,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.CreatedAt,
		&i.Blocks,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    created_at,
    blocks
FROM articles
WHERE id = $1
`

type GetArticleByIDRow struct {
	ID        pgtype.UUID
	Slug      string
	Title     string
	Excerpt   string
	Content   string
	CoverUrl  string
	Alt       pgtype.Text
	Author    pgtype.Text
	Featured  bool
	CreatedAt pgtype.Timestamp
	Blocks    []byte
}

func (q *Queries) GetArticleByID(ctx context.Context, id pgtype.UUID) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.CreatedAt,
		&i.Blocks,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    created_at,
    blocks
FROM articles
WHERE slug = $1
`

type GetArticleBySlugRow struct {
	ID        pgtype.UUID
	Slug      string
	Title     string
	Excerpt   string
	Content   string
	CoverUrl  string
	Alt       pgtype.Text
	Author    pgtype.Text
	Featured  bool
	CreatedAt pgtype.Timestamp
	Blocks    []byte
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.CreatedAt,
		&i.Blocks,
	)
	return i, err
}

const getArticles = `-- name: GetArticles :many
SELECT
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    created_at,
    blocks
FROM articles
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetArticlesParams struct {
	OffsetCount int32
	LimitCount  int32
}

type GetArticlesRow struct {
	ID        pgtype.UUID
	Slug      string
	Title     string
	Excerpt   string
	Content   string
	CoverUrl  string
	Alt       pgtype.Text
	Author    pgtype.Text
	Featured  bool
	CreatedAt pgtype.Timestamp
	Blocks    []byte
}

func (q *Queries) GetArticles(ctx context.Context, arg GetArticlesParams) ([]GetArticlesRow, error) {
	rows, err := q.db.Query(ctx, getArticles, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesRow{}
	for rows.Next() {
		var i GetArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.CoverUrl,
			&i.Alt,
			&i.Author,
			&i.Featured,
			&i.CreatedAt,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET
    slug = COALESCE($1, slug),
    title = COALESCE($2, title),
    excerpt = COALESCE($3, excerpt),
    content = COALESCE($4, content),
    cover_url = COALESCE($5, cover_url),
    alt = COALESCE($6, alt),
    author = COALESCE($7, author),
    featured = COALESCE($8, featured),
    blocks = COALESCE($9, blocks),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $10
RETURNING
    id,
    slug,
    title,
    excerpt,
    content,
    cover_url,
    alt,
    author,
    featured,
    created_at,
    updated_at,
    blocks
`

type UpdateArticleParams struct {
	Slug     string
	Title    string
	Excerpt  string
	Content  string
	CoverUrl string
	Alt      pgtype.Text
	Author   pgtype.Text
	Featured bool
	Blocks   []byte
	ID       pgtype.UUID
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Content,
		arg.CoverUrl,
		arg.Alt,
		arg.Author,
		arg.Featured,
		arg.Blocks,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverUrl,
		&i.Alt,
		&i.Author,
		&i.Featured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Blocks,
	)
	return i, err
}
