// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_query.sql

package db

import (
	"context"
)

const getCategoriesByTourID = `-- name: GetCategoriesByTourID :many
SELECT
  c.id,
  c.name
FROM tour_categories tc
  JOIN categories c ON tc.category_id = c.id
WHERE tc.tour_id = $1
`

func (q *Queries) GetCategoriesByTourID(ctx context.Context, tourID int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByTourIDs = `-- name: GetCategoriesByTourIDs :many
SELECT
  tc.tour_id,
  c.id,
  c.name
FROM tour_categories tc
  JOIN categories c ON tc.category_id = c.id
WHERE tc.tour_id = ANY($1::int[])
`

type GetCategoriesByTourIDsRow struct {
	TourID int32
	ID     int32
	Name   string
}

func (q *Queries) GetCategoriesByTourIDs(ctx context.Context, dollar_1 []int32) ([]GetCategoriesByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByTourIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoriesByTourIDsRow{}
	for rows.Next() {
		var i GetCategoriesByTourIDsRow
		if err := rows.Scan(&i.TourID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
