// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoriesByTourID = `-- name: GetCategoriesByTourID :many
SELECT
  categories.id,
  categories.name
FROM tour_categories
  JOIN categories ON tour_categories.category_id = categories.id
WHERE tour_categories.tour_id = $1
`

func (q *Queries) GetCategoriesByTourID(ctx context.Context, tourID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByTourIDs = `-- name: GetCategoriesByTourIDs :many
SELECT
  tour_categories.tour_id,
  categories.id,
  categories.name
FROM tour_categories
  JOIN categories ON tour_categories.category_id = categories.id
WHERE tour_categories.tour_id = ANY($1::uuid[])
`

type GetCategoriesByTourIDsRow struct {
	TourID pgtype.UUID
	ID     pgtype.UUID
	Name   string
}

func (q *Queries) GetCategoriesByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]GetCategoriesByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoriesByTourIDsRow{}
	for rows.Next() {
		var i GetCategoriesByTourIDsRow
		if err := rows.Scan(&i.TourID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
