// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guide_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGuideWithUserByID = `-- name: GetGuideWithUserByID :one
SELECT
  guides.id                 AS guide_id,
  guides.user_id            AS guide_user_id,
  guides.experience         AS guide_experience,
  guides.specializations    AS guide_specializations,
  guides.created_at         AS guide_created_at,
  guides.updated_at         AS guide_updated_at,

  users.id                 AS user_id,
  users.email              AS user_email,
  users.first_name         AS user_first_name,
  users.last_name          AS user_last_name,
  users.phone              AS user_phone,
  users.bio                AS user_bio,
  users.profile_pic_url    AS user_profile_pic_url,
  users.role               AS user_role,
  users.created_at         AS user_created_at,
  users.updated_at         AS user_updated_at
FROM guides
JOIN users ON guides.user_id = users.id
WHERE guides.id = $1
`

type GetGuideWithUserByIDRow struct {
	GuideID              pgtype.UUID
	GuideUserID          pgtype.UUID
	GuideExperience      pgtype.Text
	GuideSpecializations []string
	GuideCreatedAt       pgtype.Timestamp
	GuideUpdatedAt       pgtype.Timestamp
	UserID               pgtype.UUID
	UserEmail            string
	UserFirstName        string
	UserLastName         string
	UserPhone            pgtype.Text
	UserBio              pgtype.Text
	UserProfilePicUrl    pgtype.Text
	UserRole             Role
	UserCreatedAt        pgtype.Timestamp
	UserUpdatedAt        pgtype.Timestamp
}

func (q *Queries) GetGuideWithUserByID(ctx context.Context, id pgtype.UUID) (GetGuideWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getGuideWithUserByID, id)
	var i GetGuideWithUserByIDRow
	err := row.Scan(
		&i.GuideID,
		&i.GuideUserID,
		&i.GuideExperience,
		&i.GuideSpecializations,
		&i.GuideCreatedAt,
		&i.GuideUpdatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserFirstName,
		&i.UserLastName,
		&i.UserPhone,
		&i.UserBio,
		&i.UserProfilePicUrl,
		&i.UserRole,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getGuidesWithUserByIDs = `-- name: GetGuidesWithUserByIDs :many
SELECT
  guides.id                 AS guide_id,
  guides.user_id            AS guide_user_id,
  guides.experience         AS guide_experience,
  guides.specializations    AS guide_specializations,
  guides.created_at         AS guide_created_at,
  guides.updated_at         AS guide_updated_at,

  users.id                 AS user_id,
  users.email              AS user_email,
  users.first_name         AS user_first_name,
  users.last_name          AS user_last_name,
  users.phone              AS user_phone,
  users.bio                AS user_bio,
  users.profile_pic_url    AS user_profile_pic_url,
  users.role               AS user_role,
  users.created_at         AS user_created_at,
  users.updated_at         AS user_updated_at
FROM guides
JOIN users ON guides.user_id = users.id
WHERE guides.id = ANY($1::uuid[])
`

type GetGuidesWithUserByIDsRow struct {
	GuideID              pgtype.UUID
	GuideUserID          pgtype.UUID
	GuideExperience      pgtype.Text
	GuideSpecializations []string
	GuideCreatedAt       pgtype.Timestamp
	GuideUpdatedAt       pgtype.Timestamp
	UserID               pgtype.UUID
	UserEmail            string
	UserFirstName        string
	UserLastName         string
	UserPhone            pgtype.Text
	UserBio              pgtype.Text
	UserProfilePicUrl    pgtype.Text
	UserRole             Role
	UserCreatedAt        pgtype.Timestamp
	UserUpdatedAt        pgtype.Timestamp
}

func (q *Queries) GetGuidesWithUserByIDs(ctx context.Context, ids []pgtype.UUID) ([]GetGuidesWithUserByIDsRow, error) {
	rows, err := q.db.Query(ctx, getGuidesWithUserByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGuidesWithUserByIDsRow{}
	for rows.Next() {
		var i GetGuidesWithUserByIDsRow
		if err := rows.Scan(
			&i.GuideID,
			&i.GuideUserID,
			&i.GuideExperience,
			&i.GuideSpecializations,
			&i.GuideCreatedAt,
			&i.GuideUpdatedAt,
			&i.UserID,
			&i.UserEmail,
			&i.UserFirstName,
			&i.UserLastName,
			&i.UserPhone,
			&i.UserBio,
			&i.UserProfilePicUrl,
			&i.UserRole,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
