// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleADMIN  Role = "ADMIN"
	RoleCLIENT Role = "CLIENT"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Article struct {
	ID          int32
	Slug        string
	Title       string
	Excerpt     string
	Content     string
	CoverUrl    string
	Alt         pgtype.Text
	Author      pgtype.Text
	Featured    bool
	PublishedAt pgtype.Timestamp
}

type PageMetadatum struct {
	Url       string
	Tags      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID            int32
	Email         string
	Password      string
	FirstName     string
	LastName      string
	Phone         pgtype.Text
	Bio           pgtype.Text
	ProfilePicUrl pgtype.Text
	Role          Role
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
