// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_metadata_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPageMetadata = `-- name: CreatePageMetadata :one
INSERT INTO page_metadata (
  url,
  tags
)
VALUES (
    $1, $2
)
RETURNING
  url,
  tags
`

type CreatePageMetadataParams struct {
	Url  string
	Tags string
}

type CreatePageMetadataRow struct {
	Url  string
	Tags string
}

func (q *Queries) CreatePageMetadata(ctx context.Context, arg CreatePageMetadataParams) (CreatePageMetadataRow, error) {
	row := q.db.QueryRow(ctx, createPageMetadata, arg.Url, arg.Tags)
	var i CreatePageMetadataRow
	err := row.Scan(&i.Url, &i.Tags)
	return i, err
}

const deletePageMetadata = `-- name: DeletePageMetadata :exec
DELETE FROM page_metadata
WHERE url = $1
`

func (q *Queries) DeletePageMetadata(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deletePageMetadata, url)
	return err
}

const getPageMetadata = `-- name: GetPageMetadata :one
SELECT
    url,
    tags
FROM page_metadata
WHERE url = $1
`

type GetPageMetadataRow struct {
	Url  string
	Tags string
}

func (q *Queries) GetPageMetadata(ctx context.Context, url string) (GetPageMetadataRow, error) {
	row := q.db.QueryRow(ctx, getPageMetadata, url)
	var i GetPageMetadataRow
	err := row.Scan(&i.Url, &i.Tags)
	return i, err
}

const updatePageMetadata = `-- name: UpdatePageMetadata :one
UPDATE page_metadata
SET
  url = COALESCE($1, url),
  tags = COALESCE($2, tags)
WHERE url = $3
RETURNING url, tags
`

type UpdatePageMetadataParams struct {
	NewUrl  pgtype.Text
	NewTags pgtype.Text
	Url     string
}

type UpdatePageMetadataRow struct {
	Url  string
	Tags string
}

func (q *Queries) UpdatePageMetadata(ctx context.Context, arg UpdatePageMetadataParams) (UpdatePageMetadataRow, error) {
	row := q.db.QueryRow(ctx, updatePageMetadata, arg.NewUrl, arg.NewTags, arg.Url)
	var i UpdatePageMetadataRow
	err := row.Scan(&i.Url, &i.Tags)
	return i, err
}
