// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPhotosByTourID = `-- name: GetPhotosByTourID :many
SELECT
	id,
	tour_id,
	url,
	description,
	created_at
FROM photos
WHERE tour_id = $1
`

func (q *Queries) GetPhotosByTourID(ctx context.Context, tourID pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getPhotosByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotosByTourIDs = `-- name: GetPhotosByTourIDs :many
SELECT
	id,
	tour_id,
	url,
	description,
	created_at
FROM photos
WHERE tour_id = ANY($1::uuid[])
`

func (q *Queries) GetPhotosByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getPhotosByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
