// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreatePageMetadata(ctx context.Context, arg CreatePageMetadataParams) (CreatePageMetadataRow, error)
	CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePageMetadata(ctx context.Context, url string) (int64, error)
	DeleteTourByID(ctx context.Context, id int32) (int64, error)
	GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error)
	GetArticles(ctx context.Context, arg GetArticlesParams) ([]GetArticlesRow, error)
	GetCategoriesByTourID(ctx context.Context, tourID int32) ([]Category, error)
	GetCategoriesByTourIDs(ctx context.Context, dollar_1 []int32) ([]GetCategoriesByTourIDsRow, error)
	GetGuideWithUserByID(ctx context.Context, id int32) (GetGuideWithUserByIDRow, error)
	GetGuidesWithUserByIDs(ctx context.Context, dollar_1 []int32) ([]GetGuidesWithUserByIDsRow, error)
	GetPageMetadata(ctx context.Context, url string) (GetPageMetadataRow, error)
	GetPhotosByTourID(ctx context.Context, tourID int32) ([]Photo, error)
	GetPhotosByTourIDs(ctx context.Context, dollar_1 []int32) ([]Photo, error)
	GetReviewAmountAndStarAmount(ctx context.Context, tourID int32) (GetReviewAmountAndStarAmountRow, error)
	GetReviewAmountAndStarAmountByTourIDs(ctx context.Context, dollar_1 []int32) ([]GetReviewAmountAndStarAmountByTourIDsRow, error)
	GetReviewsByTourID(ctx context.Context, tourID int32) ([]Review, error)
	GetReviewsByTourIDs(ctx context.Context, dollar_1 []int32) ([]Review, error)
	GetTagsByTourID(ctx context.Context, tourID int32) ([]Tag, error)
	GetTagsByTourIDs(ctx context.Context, dollar_1 []int32) ([]GetTagsByTourIDsRow, error)
	GetTourByID(ctx context.Context, id int32) (Tour, error)
	GetTourBySlug(ctx context.Context, slug string) (Tour, error)
	GetTourDatesByTourID(ctx context.Context, tourID int32) ([]TourDate, error)
	GetTourDatesByTourIDs(ctx context.Context, dollar_1 []int32) ([]TourDate, error)
	GetTourMaterialsByTourID(ctx context.Context, tourID int32) ([]TourMaterial, error)
	GetTourMaterialsByTourIDs(ctx context.Context, dollar_1 []int32) ([]TourMaterial, error)
	GetTours(ctx context.Context, arg GetToursParams) ([]Tour, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetVideosByTourID(ctx context.Context, tourID int32) ([]Video, error)
	GetVideosByTourIDs(ctx context.Context, dollar_1 []int32) ([]Video, error)
	ResetSchema(ctx context.Context) error
	UpdatePageMetadata(ctx context.Context, arg UpdatePageMetadataParams) (UpdatePageMetadataRow, error)
	UpdateTourByID(ctx context.Context, arg UpdateTourByIDParams) (Tour, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
