// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExistsByEmail(ctx context.Context, email string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ResetSchema(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
