// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_db.sql

package db

import (
	"context"
)

const resetSchema = `-- name: ResetSchema :exec
DO $$
BEGIN
    EXECUTE 'DROP SCHEMA IF EXISTS public CASCADE';
    EXECUTE 'CREATE SCHEMA public';
END $$
`

func (q *Queries) ResetSchema(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSchema)
	return err
}
