// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRandomReviews = `-- name: GetRandomReviews :many
SELECT
    id,
    tour_id,
    user_id,
    rating,
    comment,
    user_name,
    link,
    image,
    created_at
FROM reviews
ORDER BY RANDOM()
LIMIT 20
`

type GetRandomReviewsRow struct {
	ID        pgtype.UUID
	TourID    pgtype.UUID
	UserID    pgtype.UUID
	Rating    int32
	Comment   pgtype.Text
	UserName  string
	Link      string
	Image     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetRandomReviews(ctx context.Context) ([]GetRandomReviewsRow, error) {
	rows, err := q.db.Query(ctx, getRandomReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomReviewsRow{}
	for rows.Next() {
		var i GetRandomReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.UserName,
			&i.Link,
			&i.Image,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewAmountAndStarAmount = `-- name: GetReviewAmountAndStarAmount :one
SELECT
    COUNT(*) as review_amount,
    COALESCE(ROUND(AVG(rating)::numeric, 1), 0)::float8 as star_amount
FROM reviews
WHERE tour_id = $1
`

type GetReviewAmountAndStarAmountRow struct {
	ReviewAmount int64
	StarAmount   float64
}

func (q *Queries) GetReviewAmountAndStarAmount(ctx context.Context, tourID pgtype.UUID) (GetReviewAmountAndStarAmountRow, error) {
	row := q.db.QueryRow(ctx, getReviewAmountAndStarAmount, tourID)
	var i GetReviewAmountAndStarAmountRow
	err := row.Scan(&i.ReviewAmount, &i.StarAmount)
	return i, err
}

const getReviewAmountAndStarAmountByTourIDs = `-- name: GetReviewAmountAndStarAmountByTourIDs :many
SELECT
    tour_id,
    COUNT(*) as review_amount,
    COALESCE(ROUND(AVG(rating)::numeric, 1), 0)::float8 as star_amount
FROM reviews
WHERE tour_id = ANY($1::uuid[])
GROUP BY tour_id
`

type GetReviewAmountAndStarAmountByTourIDsRow struct {
	TourID       pgtype.UUID
	ReviewAmount int64
	StarAmount   float64
}

func (q *Queries) GetReviewAmountAndStarAmountByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]GetReviewAmountAndStarAmountByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getReviewAmountAndStarAmountByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewAmountAndStarAmountByTourIDsRow{}
	for rows.Next() {
		var i GetReviewAmountAndStarAmountByTourIDsRow
		if err := rows.Scan(&i.TourID, &i.ReviewAmount, &i.StarAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsByTourID = `-- name: GetReviewsByTourID :many
SELECT
    id,
    tour_id,
    user_id,
    rating,
    comment,
    user_name,
    link,
    image,
    created_at
FROM reviews
WHERE tour_id = $1
ORDER BY created_at DESC
`

type GetReviewsByTourIDRow struct {
	ID        pgtype.UUID
	TourID    pgtype.UUID
	UserID    pgtype.UUID
	Rating    int32
	Comment   pgtype.Text
	UserName  string
	Link      string
	Image     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetReviewsByTourID(ctx context.Context, tourID pgtype.UUID) ([]GetReviewsByTourIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewsByTourIDRow{}
	for rows.Next() {
		var i GetReviewsByTourIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.UserName,
			&i.Link,
			&i.Image,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsByTourIDs = `-- name: GetReviewsByTourIDs :many
SELECT
    id,
    tour_id,
    user_id,
    rating,
    comment,
    user_name,
    link,
    image,
    created_at
FROM reviews
WHERE tour_id = ANY($1::uuid[])
ORDER BY tour_id, created_at DESC
`

type GetReviewsByTourIDsRow struct {
	ID        pgtype.UUID
	TourID    pgtype.UUID
	UserID    pgtype.UUID
	Rating    int32
	Comment   pgtype.Text
	UserName  string
	Link      string
	Image     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetReviewsByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]GetReviewsByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewsByTourIDsRow{}
	for rows.Next() {
		var i GetReviewsByTourIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.UserName,
			&i.Link,
			&i.Image,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
