// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: similar_tour_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSimilarToursByTourID = `-- name: GetSimilarToursByTourID :many
SELECT
    tours.id,
    tours.slug,
    tours.title,
    tours.description,
    tours.difficulty,
    tours.price,
    tours.program,
    tours.faq,
    tours.guide_id,
    tours.cover_url,
    tours.duration_days,
    tours.end_location,
    tours.available_months,
    tours.languages,
    tours.min_age,
    tours.start_location,
    tours.location,
    tours.group_size,
    tours.spots_left,
    tours.subtitle,
    tours.pop_up1_title,
    tours.pop_up1_description,
    tours.pop_up2_title,
    tours.pop_up2_description,
    tours.pop_up1_image_url,
    tours.pop_up2_image_url,
    tours.cta_title,
    tours.cta_description,
    tours.reviews_section_name,
    tours.created_at,
    tours.updated_at
FROM similar_tours
JOIN tours ON similar_tours.similar_tour_id = tours.id
WHERE similar_tours.tour_id = $1
`

type GetSimilarToursByTourIDRow struct {
	ID                 pgtype.UUID
	Slug               string
	Title              string
	Description        string
	Difficulty         DifficultyLevel
	Price              pgtype.Float8
	Program            []byte
	Faq                []byte
	GuideID            pgtype.UUID
	CoverUrl           pgtype.Text
	DurationDays       pgtype.Int4
	EndLocation        pgtype.Text
	AvailableMonths    []string
	Languages          []string
	MinAge             pgtype.Int4
	StartLocation      pgtype.Text
	Location           pgtype.Text
	GroupSize          pgtype.Int4
	SpotsLeft          pgtype.Int4
	Subtitle           pgtype.Text
	PopUp1Title        string
	PopUp1Description  string
	PopUp2Title        string
	PopUp2Description  string
	PopUp1ImageUrl     string
	PopUp2ImageUrl     string
	CtaTitle           string
	CtaDescription     string
	ReviewsSectionName string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) GetSimilarToursByTourID(ctx context.Context, tourID pgtype.UUID) ([]GetSimilarToursByTourIDRow, error) {
	rows, err := q.db.Query(ctx, getSimilarToursByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSimilarToursByTourIDRow{}
	for rows.Next() {
		var i GetSimilarToursByTourIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Price,
			&i.Program,
			&i.Faq,
			&i.GuideID,
			&i.CoverUrl,
			&i.DurationDays,
			&i.EndLocation,
			&i.AvailableMonths,
			&i.Languages,
			&i.MinAge,
			&i.StartLocation,
			&i.Location,
			&i.GroupSize,
			&i.SpotsLeft,
			&i.Subtitle,
			&i.PopUp1Title,
			&i.PopUp1Description,
			&i.PopUp2Title,
			&i.PopUp2Description,
			&i.PopUp1ImageUrl,
			&i.PopUp2ImageUrl,
			&i.CtaTitle,
			&i.CtaDescription,
			&i.ReviewsSectionName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
