// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTagsByTourID = `-- name: GetTagsByTourID :many
SELECT
  tags.id,
  tags.name
FROM tour_tags
  JOIN tags ON tour_tags.tag_id = tags.id
WHERE tour_tags.tour_id = $1
`

func (q *Queries) GetTagsByTourID(ctx context.Context, tourID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByTourIDs = `-- name: GetTagsByTourIDs :many
SELECT
  tour_tags.tour_id,
  tags.id,
  tags.name
FROM tour_tags
  JOIN tags ON tour_tags.tag_id = tags.id
WHERE tour_tags.tour_id = ANY($1::uuid[])
`

type GetTagsByTourIDsRow struct {
	TourID pgtype.UUID
	ID     pgtype.UUID
	Name   string
}

func (q *Queries) GetTagsByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]GetTagsByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getTagsByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsByTourIDsRow{}
	for rows.Next() {
		var i GetTagsByTourIDsRow
		if err := rows.Scan(&i.TourID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
