// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_date_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTourDatesByTourID = `-- name: GetTourDatesByTourID :many
SELECT
    id,
    tour_id,
    date_from,
    date_to,
    group_size,
    is_available,
    price,
    description,
    created_at,
    updated_at
FROM tour_dates
WHERE tour_id = $1
`

type GetTourDatesByTourIDRow struct {
	ID          pgtype.UUID
	TourID      pgtype.UUID
	DateFrom    pgtype.Timestamp
	DateTo      pgtype.Timestamp
	GroupSize   int32
	IsAvailable bool
	Price       pgtype.Float8
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) GetTourDatesByTourID(ctx context.Context, tourID pgtype.UUID) ([]GetTourDatesByTourIDRow, error) {
	rows, err := q.db.Query(ctx, getTourDatesByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTourDatesByTourIDRow{}
	for rows.Next() {
		var i GetTourDatesByTourIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.DateFrom,
			&i.DateTo,
			&i.GroupSize,
			&i.IsAvailable,
			&i.Price,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourDatesByTourIDs = `-- name: GetTourDatesByTourIDs :many
SELECT
    id,
    tour_id,
    date_from,
    date_to,
    group_size,
    is_available,
    price,
    description,
    created_at,
    updated_at
FROM tour_dates
WHERE tour_id = ANY($1::uuid[])
`

type GetTourDatesByTourIDsRow struct {
	ID          pgtype.UUID
	TourID      pgtype.UUID
	DateFrom    pgtype.Timestamp
	DateTo      pgtype.Timestamp
	GroupSize   int32
	IsAvailable bool
	Price       pgtype.Float8
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) GetTourDatesByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]GetTourDatesByTourIDsRow, error) {
	rows, err := q.db.Query(ctx, getTourDatesByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTourDatesByTourIDsRow{}
	for rows.Next() {
		var i GetTourDatesByTourIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.DateFrom,
			&i.DateTo,
			&i.GroupSize,
			&i.IsAvailable,
			&i.Price,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
