// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_included_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTourIncluded = `-- name: CreateTourIncluded :one
INSERT INTO tour_included (tour_id, included)
VALUES ($1, $2)
RETURNING id, tour_id, included, created_at
`

type CreateTourIncludedParams struct {
	TourID   pgtype.UUID
	Included string
}

func (q *Queries) CreateTourIncluded(ctx context.Context, arg CreateTourIncludedParams) (TourIncluded, error) {
	row := q.db.QueryRow(ctx, createTourIncluded, arg.TourID, arg.Included)
	var i TourIncluded
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.Included,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTourIncluded = `-- name: DeleteTourIncluded :exec
DELETE FROM tour_included WHERE id = $1
`

func (q *Queries) DeleteTourIncluded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourIncluded, id)
	return err
}

const deleteTourIncludedByTourID = `-- name: DeleteTourIncludedByTourID :exec
DELETE FROM tour_included WHERE tour_id = $1
`

func (q *Queries) DeleteTourIncludedByTourID(ctx context.Context, tourID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourIncludedByTourID, tourID)
	return err
}

const getTourIncludedByTourID = `-- name: GetTourIncludedByTourID :many
SELECT id, tour_id, included, created_at
FROM tour_included
WHERE tour_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTourIncludedByTourID(ctx context.Context, tourID pgtype.UUID) ([]TourIncluded, error) {
	rows, err := q.db.Query(ctx, getTourIncludedByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourIncluded{}
	for rows.Next() {
		var i TourIncluded
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Included,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourIncludedByTourIDs = `-- name: GetTourIncludedByTourIDs :many
SELECT id, tour_id, included, created_at
FROM tour_included
WHERE tour_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetTourIncludedByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]TourIncluded, error) {
	rows, err := q.db.Query(ctx, getTourIncludedByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourIncluded{}
	for rows.Next() {
		var i TourIncluded
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Included,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
