// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTour = `-- name: CreateTour :one
INSERT INTO tours (
    title,
    description,
    difficulty,
    program,
    price,
    start_location,
    end_location,
    duration_days,
    min_age,
    cover_url,
    languages,
    available_months,
    guide_id
) VALUES (
    $1,
    $2,
    $3::difficulty_level,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
) RETURNING
    id,
    slug,
    title,
    description,
    difficulty,
    price,
    program,
    guide_id,
    cover_url,
    duration_days,
    end_location,
    available_months,
    languages,
    min_age,
    start_location,
    created_at,
    updated_at
`

type CreateTourParams struct {
	Title           string
	Description     string
	Difficulty      DifficultyLevel
	Program         []byte
	Price           pgtype.Float8
	StartLocation   pgtype.Text
	EndLocation     pgtype.Text
	DurationDays    pgtype.Int4
	MinAge          pgtype.Int4
	CoverUrl        pgtype.Text
	Languages       []string
	AvailableMonths []string
	GuideID         pgtype.Int4
}

func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRow(ctx, createTour,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Program,
		arg.Price,
		arg.StartLocation,
		arg.EndLocation,
		arg.DurationDays,
		arg.MinAge,
		arg.CoverUrl,
		arg.Languages,
		arg.AvailableMonths,
		arg.GuideID,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Price,
		&i.Program,
		&i.GuideID,
		&i.CoverUrl,
		&i.DurationDays,
		&i.EndLocation,
		&i.AvailableMonths,
		&i.Languages,
		&i.MinAge,
		&i.StartLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTourByID = `-- name: DeleteTourByID :execrows
DELETE FROM tours
WHERE id = $1
`

func (q *Queries) DeleteTourByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTourByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTourByID = `-- name: GetTourByID :one
SELECT
    id,
    slug,
    title,
    description,
    difficulty,
    price,
    program,
    guide_id,
    cover_url,
    duration_days,
    end_location,
    available_months,
    languages,
    min_age,
    start_location,
    created_at,
    updated_at
FROM tours
WHERE id = $1
`

func (q *Queries) GetTourByID(ctx context.Context, id int32) (Tour, error) {
	row := q.db.QueryRow(ctx, getTourByID, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Price,
		&i.Program,
		&i.GuideID,
		&i.CoverUrl,
		&i.DurationDays,
		&i.EndLocation,
		&i.AvailableMonths,
		&i.Languages,
		&i.MinAge,
		&i.StartLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTourBySlug = `-- name: GetTourBySlug :one
SELECT
    id,
    slug,
    title,
    description,
    difficulty,
    price,
    program,
    guide_id,
    cover_url,
    duration_days,
    end_location,
    available_months,
    languages,
    min_age,
    start_location,
    created_at,
    updated_at
FROM tours
WHERE slug = $1
`

func (q *Queries) GetTourBySlug(ctx context.Context, slug string) (Tour, error) {
	row := q.db.QueryRow(ctx, getTourBySlug, slug)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Price,
		&i.Program,
		&i.GuideID,
		&i.CoverUrl,
		&i.DurationDays,
		&i.EndLocation,
		&i.AvailableMonths,
		&i.Languages,
		&i.MinAge,
		&i.StartLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTours = `-- name: GetTours :many
SELECT DISTINCT
    t.id,
    t.slug,
    t.title,
    t.description,
    t.difficulty,
    t.price,
    t.program,
    t.guide_id,
    t.cover_url,
    t.duration_days,
    t.end_location,
    t.available_months,
    t.languages,
    t.min_age,
    t.start_location,
    t.created_at,
    t.updated_at
FROM tours t
LEFT JOIN tour_dates td ON t.id = td.tour_id AND td.is_available = TRUE
WHERE
    ($3::text IS NULL
        OR t.start_location ILIKE '%' || $3::text || '%'
        OR t.end_location ILIKE '%' || $3::text || '%')
    AND ($4::timestamp IS NULL OR td.date >= $4::timestamp)
    AND ($5::timestamp IS NULL OR td.date <= $5::timestamp)
    AND ($6::int IS NULL OR td.group_size >= $6::int)
    AND ($7::float IS NULL OR t.price >= $7::float)
    AND ($8::float IS NULL OR t.price <= $8::float)
    AND ($9::int[] IS NULL OR EXTRACT(MONTH FROM td.date)::int = ANY($9::int[]))
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type GetToursParams struct {
	Limit        int32
	Offset       int32
	Location     pgtype.Text
	DateFrom     pgtype.Timestamp
	DateTo       pgtype.Timestamp
	GroupSize    pgtype.Int4
	PriceMin     pgtype.Float8
	PriceMax     pgtype.Float8
	SeasonMonths []int32
}

func (q *Queries) GetTours(ctx context.Context, arg GetToursParams) ([]Tour, error) {
	rows, err := q.db.Query(ctx, getTours,
		arg.Limit,
		arg.Offset,
		arg.Location,
		arg.DateFrom,
		arg.DateTo,
		arg.GroupSize,
		arg.PriceMin,
		arg.PriceMax,
		arg.SeasonMonths,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tour{}
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Price,
			&i.Program,
			&i.GuideID,
			&i.CoverUrl,
			&i.DurationDays,
			&i.EndLocation,
			&i.AvailableMonths,
			&i.Languages,
			&i.MinAge,
			&i.StartLocation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTourByID = `-- name: UpdateTourByID :one
UPDATE tours
SET
    title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    description = COALESCE($3, description),
    difficulty = COALESCE($4::difficulty_level, difficulty),
    program = COALESCE($5, program),
    price = COALESCE($6, price),
    start_location = COALESCE($7, start_location),
    end_location = COALESCE($8, end_location),
    duration_days = COALESCE($9, duration_days),
    min_age = COALESCE($10, min_age),
    cover_url = COALESCE($11, cover_url),
    languages = COALESCE($12, languages),
    available_months = COALESCE($13, available_months),
    guide_id = COALESCE($14, guide_id),
    updated_at = NOW()
WHERE id = $15
RETURNING
    id,
    slug,
    title,
    description,
    difficulty,
    price,
    program,
    guide_id,
    cover_url,
    duration_days,
    end_location,
    available_months,
    languages,
    min_age,
    start_location,
    created_at,
    updated_at
`

type UpdateTourByIDParams struct {
	Title           pgtype.Text
	Slug            pgtype.Text
	Description     pgtype.Text
	Difficulty      NullDifficultyLevel
	Program         []byte
	Price           pgtype.Float8
	StartLocation   pgtype.Text
	EndLocation     pgtype.Text
	DurationDays    pgtype.Int4
	MinAge          pgtype.Int4
	CoverUrl        pgtype.Text
	Languages       []string
	AvailableMonths []string
	GuideID         pgtype.Int4
	ID              int32
}

func (q *Queries) UpdateTourByID(ctx context.Context, arg UpdateTourByIDParams) (Tour, error) {
	row := q.db.QueryRow(ctx, updateTourByID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Difficulty,
		arg.Program,
		arg.Price,
		arg.StartLocation,
		arg.EndLocation,
		arg.DurationDays,
		arg.MinAge,
		arg.CoverUrl,
		arg.Languages,
		arg.AvailableMonths,
		arg.GuideID,
		arg.ID,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Price,
		&i.Program,
		&i.GuideID,
		&i.CoverUrl,
		&i.DurationDays,
		&i.EndLocation,
		&i.AvailableMonths,
		&i.Languages,
		&i.MinAge,
		&i.StartLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
