// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_activity_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTourActivity = `-- name: CreateTourActivity :one
INSERT INTO tour_activities (tour_id, activity)
VALUES ($1, $2)
RETURNING id, tour_id, activity, created_at
`

type CreateTourActivityParams struct {
	TourID   pgtype.UUID
	Activity string
}

func (q *Queries) CreateTourActivity(ctx context.Context, arg CreateTourActivityParams) (TourActivity, error) {
	row := q.db.QueryRow(ctx, createTourActivity, arg.TourID, arg.Activity)
	var i TourActivity
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.Activity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTourActivitiesByTourID = `-- name: DeleteTourActivitiesByTourID :exec
DELETE FROM tour_activities WHERE tour_id = $1
`

func (q *Queries) DeleteTourActivitiesByTourID(ctx context.Context, tourID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourActivitiesByTourID, tourID)
	return err
}

const deleteTourActivity = `-- name: DeleteTourActivity :exec
DELETE FROM tour_activities WHERE id = $1
`

func (q *Queries) DeleteTourActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourActivity, id)
	return err
}

const getTourActivitiesByTourID = `-- name: GetTourActivitiesByTourID :many
SELECT id, tour_id, activity, created_at
FROM tour_activities
WHERE tour_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTourActivitiesByTourID(ctx context.Context, tourID pgtype.UUID) ([]TourActivity, error) {
	rows, err := q.db.Query(ctx, getTourActivitiesByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourActivity{}
	for rows.Next() {
		var i TourActivity
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Activity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourActivitiesByTourIDs = `-- name: GetTourActivitiesByTourIDs :many
SELECT id, tour_id, activity, created_at
FROM tour_activities
WHERE tour_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetTourActivitiesByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]TourActivity, error) {
	rows, err := q.db.Query(ctx, getTourActivitiesByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourActivity{}
	for rows.Next() {
		var i TourActivity
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Activity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
