// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_summary_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTourSummary = `-- name: CreateTourSummary :one
INSERT INTO tour_summary (tour_id, name, value)
VALUES ($1, $2, $3)
RETURNING id, tour_id, name, value, created_at
`

type CreateTourSummaryParams struct {
	TourID pgtype.UUID
	Name   string
	Value  string
}

func (q *Queries) CreateTourSummary(ctx context.Context, arg CreateTourSummaryParams) (TourSummary, error) {
	row := q.db.QueryRow(ctx, createTourSummary, arg.TourID, arg.Name, arg.Value)
	var i TourSummary
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTourSummary = `-- name: DeleteTourSummary :exec
DELETE FROM tour_summary WHERE id = $1
`

func (q *Queries) DeleteTourSummary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourSummary, id)
	return err
}

const deleteTourSummaryByTourID = `-- name: DeleteTourSummaryByTourID :exec
DELETE FROM tour_summary WHERE tour_id = $1
`

func (q *Queries) DeleteTourSummaryByTourID(ctx context.Context, tourID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTourSummaryByTourID, tourID)
	return err
}

const getTourSummaryByTourID = `-- name: GetTourSummaryByTourID :many
SELECT id, tour_id, name, value, created_at
FROM tour_summary
WHERE tour_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTourSummaryByTourID(ctx context.Context, tourID pgtype.UUID) ([]TourSummary, error) {
	rows, err := q.db.Query(ctx, getTourSummaryByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourSummary{}
	for rows.Next() {
		var i TourSummary
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourSummaryByTourIDs = `-- name: GetTourSummaryByTourIDs :many
SELECT id, tour_id, name, value, created_at
FROM tour_summary
WHERE tour_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetTourSummaryByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]TourSummary, error) {
	rows, err := q.db.Query(ctx, getTourSummaryByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourSummary{}
	for rows.Next() {
		var i TourSummary
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
