// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_date_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTourDatesByTourID = `-- name: GetTourDatesByTourID :many
SELECT
    id,
    tour_id,
    date_from,
    date_to,
    group_size,
    is_available,
    created_at,
    updated_at
FROM tour_dates
WHERE tour_id = $1
`

func (q *Queries) GetTourDatesByTourID(ctx context.Context, tourID pgtype.UUID) ([]TourDate, error) {
	rows, err := q.db.Query(ctx, getTourDatesByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourDate{}
	for rows.Next() {
		var i TourDate
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.DateFrom,
			&i.DateTo,
			&i.GroupSize,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourDatesByTourIDs = `-- name: GetTourDatesByTourIDs :many
SELECT
    id,
    tour_id,
    date_from,
    date_to,
    group_size,
    is_available,
    created_at,
    updated_at
FROM tour_dates
WHERE tour_id = ANY($1::uuid[])
`

func (q *Queries) GetTourDatesByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]TourDate, error) {
	rows, err := q.db.Query(ctx, getTourDatesByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourDate{}
	for rows.Next() {
		var i TourDate
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.DateFrom,
			&i.DateTo,
			&i.GroupSize,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
