// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_material_query.sql

package db

import (
	"context"
)

const getTourMaterialsByTourID = `-- name: GetTourMaterialsByTourID :many
SELECT
    id,
    tour_id,
    title,
    url,
    type,
    created_at
FROM tour_materials
WHERE tour_id = $1
`

func (q *Queries) GetTourMaterialsByTourID(ctx context.Context, tourID int32) ([]TourMaterial, error) {
	rows, err := q.db.Query(ctx, getTourMaterialsByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourMaterial{}
	for rows.Next() {
		var i TourMaterial
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Title,
			&i.Url,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
