// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password,
    first_name,
    last_name,
    phone,
    bio,
    profile_pic_url,
    role
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
  id,
  email,
  password,
  first_name,
  last_name,
  phone,
  bio,
  profile_pic_url,
  role,
  created_at,
  updated_at
`

type CreateUserParams struct {
	Email         string
	Password      string
	FirstName     string
	LastName      string
	Phone         pgtype.Text
	Bio           pgtype.Text
	ProfilePicUrl pgtype.Text
	Role          Role
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Bio,
		arg.ProfilePicUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Bio,
		&i.ProfilePicUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password,
    first_name,
    last_name,
    phone,
    bio,
    profile_pic_url,
    role,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Bio,
		&i.ProfilePicUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    password,
    first_name,
    last_name,
    phone,
    bio,
    profile_pic_url,
    role,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Bio,
		&i.ProfilePicUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id,
    email,
    password,
    first_name,
    last_name,
    phone,
    bio,
    profile_pic_url,
    role,
    created_at,
    updated_at
FROM users
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetUsersParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Bio,
			&i.ProfilePicUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    phone = COALESCE($3, phone),
    bio = COALESCE($4, bio),
    profile_pic_url = COALESCE($5, profile_pic_url)
WHERE id = $6
RETURNING
  id,
  email,
  password,
  first_name,
  last_name,
  phone,
  bio,
  profile_pic_url,
  role,
  created_at,
  updated_at
`

type UpdateUserParams struct {
	FirstName     pgtype.Text
	LastName      pgtype.Text
	Phone         pgtype.Text
	Bio           pgtype.Text
	ProfilePicUrl pgtype.Text
	ID            pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Bio,
		arg.ProfilePicUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Bio,
		&i.ProfilePicUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $1
WHERE id = $2
RETURNING
  id,
  email,
  password,
  first_name,
  last_name,
  phone,
  bio,
  profile_pic_url,
  role,
  created_at,
  updated_at
`

type UpdateUserPasswordParams struct {
	Password string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Bio,
		&i.ProfilePicUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
