// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideosByTourID = `-- name: GetVideosByTourID :many
SELECT
  id,
  tour_id,
  url,
  description,
  created_at
FROM videos
WHERE tour_id = $1
`

func (q *Queries) GetVideosByTourID(ctx context.Context, tourID pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByTourID, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosByTourIDs = `-- name: GetVideosByTourIDs :many
SELECT
  id,
  tour_id,
  url,
  description,
  created_at
FROM videos
WHERE tour_id = ANY($1::uuid[])
`

func (q *Queries) GetVideosByTourIDs(ctx context.Context, tourIds []pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByTourIDs, tourIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
