import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.DOCS_PORT || 8080;

// Serve static files from autogenerated directory
app.use(express.static(path.join(__dirname, '../autogenerated')));

// Redirect root to documentation
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../autogenerated/index.html'));
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Documentation server is running' });
});

app.listen(PORT, () => {
  console.log(`📚 Documentation server running at http://localhost:${PORT}`);
  console.log(`📖 Open http://localhost:${PORT} in your browser`);
  console.log(`🏥 Health check: http://localhost:${PORT}/health`);
}); 