import express from "express";
import path from "path";
import process from "process";

const __dirname = process.cwd();

const app = express();
const PORT = process.env.DOCS_PORT || 8080;

// Serve static files from autogenerated directory
app.use(express.static(path.join(__dirname, "../autogenerated")));

// Redirect root to documentation
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "../autogenerated/index.html"));
});

// Health check endpoint
app.get("/health", (req, res) => {
  res.json({ status: "ok", message: "Documentation server is running" });
});

app.listen(PORT, () => {
});
