FROM node:22.7.0-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.8.0 --activate
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY pt-general/package.json pt-general/package.json
RUN pnpm install --filter pt-general --frozen-lockfile
COPY pt-general ./pt-general
RUN pnpm --filter pt-general build
CMD ["pnpm", "--filter", "pt-general", "start"]

