/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoArticleDetailDTO,
  DtoArticleSummaryDTO,
} from '../models/index';
import {
    DtoArticleDetailDTOFromJSON,
    DtoArticleDetailDTOToJSON,
    DtoArticleSummaryDTOFromJSON,
    DtoArticleSummaryDTOToJSON,
} from '../models/index';

export interface ArticlesGetRequest {
    page?: number;
    limit?: number;
}

export interface ArticlesSlugGetRequest {
    slug: string;
}

/**
 * 
 */
export class ArticlesApi extends runtime.BaseAPI {

    /**
     * Get a paginated list of articles
     * Get all articles
     */
    async articlesGetRaw(requestParameters: ArticlesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DtoArticleSummaryDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/articles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DtoArticleSummaryDTOFromJSON));
    }

    /**
     * Get a paginated list of articles
     * Get all articles
     */
    async articlesGet(requestParameters: ArticlesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DtoArticleSummaryDTO>> {
        const response = await this.articlesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed article information by slug
     * Get article by slug
     */
    async articlesSlugGetRaw(requestParameters: ArticlesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoArticleDetailDTO>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling articlesSlugGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/articles/{slug}`;
        urlPath = urlPath.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoArticleDetailDTOFromJSON(jsonValue));
    }

    /**
     * Get detailed article information by slug
     * Get article by slug
     */
    async articlesSlugGet(requestParameters: ArticlesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoArticleDetailDTO> {
        const response = await this.articlesSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
