/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DomainLogin,
  DomainRegister,
  DtoAuthResponse,
  DtoChangePasswordDTO,
  DtoUserDTO,
} from '../models/index';
import {
    DomainLoginFromJSON,
    DomainLoginToJSON,
    DomainRegisterFromJSON,
    DomainRegisterToJSON,
    DtoAuthResponseFromJSON,
    DtoAuthResponseToJSON,
    DtoChangePasswordDTOFromJSON,
    DtoChangePasswordDTOToJSON,
    DtoUserDTOFromJSON,
    DtoUserDTOToJSON,
} from '../models/index';

export interface AuthChangePasswordPostRequest {
    request: DtoChangePasswordDTO;
}

export interface AuthLoginPostRequest {
    request: DomainLogin;
}

export interface AuthProfilePutRequest {
    firstName?: string;
    lastName?: string;
    phone?: string;
    bio?: string;
    avatar?: Blob;
}

export interface AuthRegisterPostRequest {
    request: DomainRegister;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Change the authenticated user\'s password
     * Change user password
     */
    async authChangePasswordPostRaw(requestParameters: AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoUserDTO>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/auth/change-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoChangePasswordDTOToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoUserDTOFromJSON(jsonValue));
    }

    /**
     * Change the authenticated user\'s password
     * Change user password
     */
    async authChangePasswordPost(requestParameters: AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoUserDTO> {
        const response = await this.authChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Authenticate user and return JWT token
     * Login user
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoAuthResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DomainLoginToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoAuthResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate user and return JWT token
     * Login user
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoAuthResponse> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the authenticated user\'s profile
     * Get user profile
     */
    async authProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoUserDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/auth/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoUserDTOFromJSON(jsonValue));
    }

    /**
     * Get the authenticated user\'s profile
     * Get user profile
     */
    async authProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoUserDTO> {
        const response = await this.authProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update the authenticated user\'s profile (multipart/form-data for avatar upload)
     * Update user profile
     */
    async authProfilePutRaw(requestParameters: AuthProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoUserDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['firstName'] != null) {
            formParams.append('firstName', requestParameters['firstName'] as any);
        }

        if (requestParameters['lastName'] != null) {
            formParams.append('lastName', requestParameters['lastName'] as any);
        }

        if (requestParameters['phone'] != null) {
            formParams.append('phone', requestParameters['phone'] as any);
        }

        if (requestParameters['bio'] != null) {
            formParams.append('bio', requestParameters['bio'] as any);
        }

        if (requestParameters['avatar'] != null) {
            formParams.append('avatar', requestParameters['avatar'] as any);
        }


        let urlPath = `/auth/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoUserDTOFromJSON(jsonValue));
    }

    /**
     * Update the authenticated user\'s profile (multipart/form-data for avatar upload)
     * Update user profile
     */
    async authProfilePut(requestParameters: AuthProfilePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoUserDTO> {
        const response = await this.authProfilePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new user account
     * Register a new user
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoAuthResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DomainRegisterToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoAuthResponseFromJSON(jsonValue));
    }

    /**
     * Create a new user account
     * Register a new user
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoAuthResponse> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
