/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DomainBookingRequest,
  DtoCreateBookingResponse,
} from '../models/index';
import {
    DomainBookingRequestFromJSON,
    DomainBookingRequestToJSON,
    DtoCreateBookingResponseFromJSON,
    DtoCreateBookingResponseToJSON,
} from '../models/index';

export interface BookingsPostRequest {
    request: DomainBookingRequest;
}

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     * Create a new booking request and get redirect URL for payment
     * Create a new booking request
     */
    async bookingsPostRaw(requestParameters: BookingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoCreateBookingResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling bookingsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DomainBookingRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoCreateBookingResponseFromJSON(jsonValue));
    }

    /**
     * Create a new booking request and get redirect URL for payment
     * Create a new booking request
     */
    async bookingsPost(requestParameters: BookingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoCreateBookingResponse> {
        const response = await this.bookingsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
