/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoContactMeRequest,
  DtoContactMeResponse,
} from '../models/index';
import {
    DtoContactMeRequestFromJSON,
    DtoContactMeRequestToJSON,
    DtoContactMeResponseFromJSON,
    DtoContactMeResponseToJSON,
} from '../models/index';

export interface ContactMePostRequest {
    request: DtoContactMeRequest;
}

/**
 * 
 */
export class ContactApi extends runtime.BaseAPI {

    /**
     * Submit a contact me request with name and phone number
     * Submit contact me request
     */
    async contactMePostRaw(requestParameters: ContactMePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoContactMeResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling contactMePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/contact/me`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoContactMeRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoContactMeResponseFromJSON(jsonValue));
    }

    /**
     * Submit a contact me request with name and phone number
     * Submit contact me request
     */
    async contactMePost(requestParameters: ContactMePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoContactMeResponse> {
        const response = await this.contactMePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
