/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DomainPageMetadata,
  DtoUpdatePageMetadataRequest,
} from '../models/index';
import {
    DomainPageMetadataFromJSON,
    DomainPageMetadataToJSON,
    DtoUpdatePageMetadataRequestFromJSON,
    DtoUpdatePageMetadataRequestToJSON,
} from '../models/index';

export interface PageMetadataDeleteRequest {
    url: string;
}

export interface PageMetadataGetRequest {
    url: string;
}

export interface PageMetadataPatchRequest {
    request: DtoUpdatePageMetadataRequest;
}

export interface PageMetadataPostRequest {
    request: DomainPageMetadata;
}

/**
 * 
 */
export class PageMetadataApi extends runtime.BaseAPI {

    /**
     * Delete metadata for a page URL (requires admin role)
     * Delete page metadata (Admin only)
     */
    async pageMetadataDeleteRaw(requestParameters: PageMetadataDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling pageMetadataDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/page-metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete metadata for a page URL (requires admin role)
     * Delete page metadata (Admin only)
     */
    async pageMetadataDelete(requestParameters: PageMetadataDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pageMetadataDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get metadata for a specific page URL
     * Get page metadata
     */
    async pageMetadataGetRaw(requestParameters: PageMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainPageMetadata>> {
        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling pageMetadataGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/page-metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainPageMetadataFromJSON(jsonValue));
    }

    /**
     * Get metadata for a specific page URL
     * Get page metadata
     */
    async pageMetadataGet(requestParameters: PageMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainPageMetadata> {
        const response = await this.pageMetadataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update metadata for a page URL (requires admin role)
     * Update page metadata (Admin only)
     */
    async pageMetadataPatchRaw(requestParameters: PageMetadataPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainPageMetadata>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling pageMetadataPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/page-metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DtoUpdatePageMetadataRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainPageMetadataFromJSON(jsonValue));
    }

    /**
     * Update metadata for a page URL (requires admin role)
     * Update page metadata (Admin only)
     */
    async pageMetadataPatch(requestParameters: PageMetadataPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainPageMetadata> {
        const response = await this.pageMetadataPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create metadata for a page URL (requires admin role)
     * Create page metadata (Admin only)
     */
    async pageMetadataPostRaw(requestParameters: PageMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainPageMetadata>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling pageMetadataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/page-metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DomainPageMetadataToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainPageMetadataFromJSON(jsonValue));
    }

    /**
     * Create metadata for a page URL (requires admin role)
     * Create page metadata (Admin only)
     */
    async pageMetadataPost(requestParameters: PageMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainPageMetadata> {
        const response = await this.pageMetadataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
