/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DomainReview,
} from '../models/index';
import {
    DomainReviewFromJSON,
    DomainReviewToJSON,
} from '../models/index';

/**
 * 
 */
export class ReviewsApi extends runtime.BaseAPI {

    /**
     * Get 20 reviews from the database for the main page
     * Get 20 reviews for main page
     */
    async reviewsMainGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DomainReview>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reviews/main`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DomainReviewFromJSON));
    }

    /**
     * Get 20 reviews from the database for the main page
     * Get 20 reviews for main page
     */
    async reviewsMainGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DomainReview>> {
        const response = await this.reviewsMainGetRaw(initOverrides);
        return await response.value();
    }

}
