/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoSubscribeRequest,
  DtoSubscribeResponse,
} from '../models/index';
import {
    DtoSubscribeRequestFromJSON,
    DtoSubscribeRequestToJSON,
    DtoSubscribeResponseFromJSON,
    DtoSubscribeResponseToJSON,
} from '../models/index';

export interface SubscribePostRequest {
    request: DtoSubscribeRequest;
}

/**
 * 
 */
export class SubscribeApi extends runtime.BaseAPI {

    /**
     * Subscribe to newsletter with email address
     * Subscribe to newsletter
     */
    async subscribePostRaw(requestParameters: SubscribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoSubscribeResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling subscribePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscribe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoSubscribeRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoSubscribeResponseFromJSON(jsonValue));
    }

    /**
     * Subscribe to newsletter with email address
     * Subscribe to newsletter
     */
    async subscribePost(requestParameters: SubscribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoSubscribeResponse> {
        const response = await this.subscribePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
