/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DomainTour,
  DomainTourFull,
  DtoCreateTourRequest,
  DtoUpdateTourRequest,
} from '../models/index';
import {
    DomainTourFromJSON,
    DomainTourToJSON,
    DomainTourFullFromJSON,
    DomainTourFullToJSON,
    DtoCreateTourRequestFromJSON,
    DtoCreateTourRequestToJSON,
    DtoUpdateTourRequestFromJSON,
    DtoUpdateTourRequestToJSON,
} from '../models/index';

export interface ToursGetRequest {
    page?: number;
    limit?: number;
    location?: string;
    dateFrom?: string;
    dateTo?: string;
    groupSize?: number;
    priceMin?: number;
    priceMax?: number;
    season?: string;
}

export interface ToursIdDeleteRequest {
    id: number;
}

export interface ToursIdGetRequest {
    id: number;
}

export interface ToursIdPatchRequest {
    id: number;
    request: DtoUpdateTourRequest;
}

export interface ToursPostRequest {
    request: DtoCreateTourRequest;
}

export interface ToursSlugSlugGetRequest {
    slug: string;
}

/**
 * 
 */
export class ToursApi extends runtime.BaseAPI {

    /**
     * Get a paginated list of tours with optional filters (location, date range, group size, price range, season)
     * Get all tours
     */
    async toursGetRaw(requestParameters: ToursGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DomainTour>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['dateFrom'] = requestParameters['dateFrom'];
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['dateTo'] = requestParameters['dateTo'];
        }

        if (requestParameters['groupSize'] != null) {
            queryParameters['groupSize'] = requestParameters['groupSize'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season'] = requestParameters['season'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tours`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DomainTourFromJSON));
    }

    /**
     * Get a paginated list of tours with optional filters (location, date range, group size, price range, season)
     * Get all tours
     */
    async toursGet(requestParameters: ToursGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DomainTour>> {
        const response = await this.toursGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a tour by ID (requires guide or admin role)
     * Delete tour by ID (Guide/Admin only)
     */
    async toursIdDeleteRaw(requestParameters: ToursIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toursIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/tours/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a tour by ID (requires guide or admin role)
     * Delete tour by ID (Guide/Admin only)
     */
    async toursIdDelete(requestParameters: ToursIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.toursIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get full tour information by ID including guide, dates, photos, videos, materials, tags, and categories
     * Get tour by ID
     */
    async toursIdGetRaw(requestParameters: ToursIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainTourFull>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toursIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tours/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTourFullFromJSON(jsonValue));
    }

    /**
     * Get full tour information by ID including guide, dates, photos, videos, materials, tags, and categories
     * Get tour by ID
     */
    async toursIdGet(requestParameters: ToursIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTourFull> {
        const response = await this.toursIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update tour information by ID (requires guide or admin role)
     * Update tour by ID (Guide/Admin only)
     */
    async toursIdPatchRaw(requestParameters: ToursIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainTour>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toursIdPatch().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling toursIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/tours/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DtoUpdateTourRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTourFromJSON(jsonValue));
    }

    /**
     * Update tour information by ID (requires guide or admin role)
     * Update tour by ID (Guide/Admin only)
     */
    async toursIdPatch(requestParameters: ToursIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTour> {
        const response = await this.toursIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new tour (requires guide or admin role)
     * Create a new tour (Guide/Admin only)
     */
    async toursPostRaw(requestParameters: ToursPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainTour>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling toursPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/tours`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoCreateTourRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTourFromJSON(jsonValue));
    }

    /**
     * Create a new tour (requires guide or admin role)
     * Create a new tour (Guide/Admin only)
     */
    async toursPost(requestParameters: ToursPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTour> {
        const response = await this.toursPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get full tour information by slug including guide, dates, photos, videos, materials, tags, and categories
     * Get tour by slug
     */
    async toursSlugSlugGetRaw(requestParameters: ToursSlugSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainTourFull>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling toursSlugSlugGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tours/slug/{slug}`;
        urlPath = urlPath.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTourFullFromJSON(jsonValue));
    }

    /**
     * Get full tour information by slug including guide, dates, photos, videos, materials, tags, and categories
     * Get tour by slug
     */
    async toursSlugSlugGet(requestParameters: ToursSlugSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTourFull> {
        const response = await this.toursSlugSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
