/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoPublicProfileDTO,
  DtoUserDTO,
} from '../models/index';
import {
    DtoPublicProfileDTOFromJSON,
    DtoPublicProfileDTOToJSON,
    DtoUserDTOFromJSON,
    DtoUserDTOToJSON,
} from '../models/index';

export interface UsersGetRequest {
    page?: number;
    limit?: number;
}

export interface UsersIdPublicGetRequest {
    id: number;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Get a paginated list of all users (requires admin role)
     * Get all users (Admin only)
     */
    async usersGetRaw(requestParameters: UsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DtoUserDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DtoUserDTOFromJSON));
    }

    /**
     * Get a paginated list of all users (requires admin role)
     * Get all users (Admin only)
     */
    async usersGet(requestParameters: UsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DtoUserDTO>> {
        const response = await this.usersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get public profile information for a user by ID
     * Get public user profile
     */
    async usersIdPublicGetRaw(requestParameters: UsersIdPublicGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DtoPublicProfileDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdPublicGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{id}/public`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DtoPublicProfileDTOFromJSON(jsonValue));
    }

    /**
     * Get public profile information for a user by ID
     * Get public user profile
     */
    async usersIdPublicGet(requestParameters: UsersIdPublicGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DtoPublicProfileDTO> {
        const response = await this.usersIdPublicGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
