/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Webhook endpoint for PayPal deposit succeeded events
     * Handle PayPal deposit succeeded webhook
     */
    async generalBookingsDepositSucceededPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/general/bookings/deposit-succeeded`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Webhook endpoint for PayPal deposit succeeded events
     * Handle PayPal deposit succeeded webhook
     */
    async generalBookingsDepositSucceededPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.generalBookingsDepositSucceededPostRaw(initOverrides);
        return await response.value();
    }

}
