export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  ADMIN: "/admin",
  TOURS: "/tours",
  TOUR_DETAILS: "/tours/:id",
  CART: "/cart",
  CONTACT: "/contact",
  ARTICLES: "/articles",
  PROFILE: "/profile",
  NOT_FOUND: "*",
  ADMIN_CREATE_TOUR: "/admin/tours",
  ADMIN_EDIT_TOUR: "/admin/tours/:id",
  ADMIN_TOUR_CONTINUE: "/admin/tour/:id/continue",
};
