FROM node:22.7.0-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.8.0 --activate
COPY ./pnpm-lock.yaml ./pnpm-workspace.yaml ./package.json ./
COPY ./pt-web/package.json ./pt-web/package.json
RUN pnpm install --filter pt-web --frozen-lockfile
COPY ./pt-web ./pt-web
WORKDIR /app/pt-web
EXPOSE 5174
CMD ["pnpm", "run", "dev"]
