version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    # ==================== Баги и утечки ресурсов ====================

    # Проверяет, что http.Response.Body всегда закрывается.
    # Без этого горутина и соединение висят до таймаута.
    - bodyclose

    # HTTP-запросы должны использовать context.Context.
    # Иначе graceful shutdown не сможет отменить запрос.
    - noctx

    # После итерации по sql.Rows нужно проверить rows.Err().
    # Без этого ошибки БД молча проглатываются.
    - rowserrcheck

    # sql.Rows и sql.Stmt должны быть закрыты.
    # Утечка соединений убивает пул и ложит БД.
    - sqlclosecheck

    # Ловит time.Second * time.Second и подобные ошибки.
    # Результат — наносекунды вместо секунд.
    - durationcheck

    # Находит return nil когда err != nil.
    # Классическая копипаста: проверили ошибку, вернули не то.
    - nilerr

    # ==================== Работа с ошибками (Go 1.13+) ====================

    # Проверяет правильное использование error wrapping:
    # - errors.Is() вместо == для сравнения
    # - errors.As() вместо type assertion
    # - %w вместо %v в fmt.Errorf
    - errorlint

    # ==================== Безопасность ====================

    # Сканер безопасности: hardcoded пароли, SQL injection,
    # слабый math/rand вместо crypto/rand, небезопасный TLS и др.
    - gosec

    # ==================== Качество и чистота кода ====================

    # Мощный мета-линтер с кучей проверок:
    # - подозрительные конструкции (diagnostic)
    # - неоптимальный код (performance)
    - gocritic

    # Убирает лишние преобразования типов: int(x) где x уже int.
    - unconvert

    # Опечатки в комментариях и строках: "calback" -> "callback".
    - misspell

    # Находит присваивания, результат которых не используется.
    # x = 1; x = 2 — первое присваивание бесполезно.
    - wastedassign

    # Находит неиспользуемые параметры функций.
    # Часто указывает на недописанный код или лишние аргументы.
    - unparam

    # Затенение встроенных идентификаторов: len := 5, true := false.
    # Компилируется, но сломает голову при отладке.
    - predeclared

    # Предлагает предвыделять слайсы, если размер известен заранее.
    # make([]T, 0) + append в цикле → make([]T, 0, n)
    - prealloc

    # Находит лишние аллокации при конвертации []byte ↔ string.
    - copyloopvar

    # Проверяет, что все ошибки проверены (более строгий чем errcheck).
    - errchkjson # особенно для json.Marshal/Unmarshal

    # Находит пустые ветки if err != nil { } без обработки.
    - reassign

    # ==================== Современный Go ====================

    # Предлагает современные альтернативы:
    # - slices.Contains вместо цикла с проверкой
    # - maps.Clone вместо ручного копирования
    # - min/max вместо if-else (Go 1.21+)
    - modernize

  disable:
    - gocritic

  settings:
    gocritic:
      enabled-tags:
        - diagnostic # вероятные баги
        - performance # неоптимальный код

    errcheck:
      check-type-assertions: true # x := y.(Type) без проверки ok
      check-blank: true # _ = mayFail() — явное игнорирование
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync

    govet:
      enable-all: true
      disable:
        - shadow

    gosec:
      excludes:
        - G104 # "unhandled error" — дублирует errcheck
        - G203
        - G109

  exclusions:
    presets:
      - common-false-positives # известные ложные срабатывания
      - std-error-handling # игнор ошибок в defer close и т.п.
    rules:
      # В тестах можно расслабиться
      - path: _test\.go
        linters:
          - bodyclose # тестовые http клиенты часто не закрывают body
          - gosec # тестовые данные не требуют crypto/rand
          - noctx # в тестах контекст часто не нужен
          - errcheck # в тестах часто игнорируем ошибки setup/teardown

formatters:
  enable:
    # goimports = gofmt + сортировка импортов + удаление лишних
    - goimports

  settings:
    goimports:
      local-prefixes:
        # Локальные импорты будут отделены пустой строкой.
        - esl-craft

issues:
  # Не обрезать вывод однотипных ошибок.
  # По умолчанию 3 — слишком мало для первого запуска.
  max-same-issues: 50
