version: "2"

linters:
  enable:
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - copyloopvar # detects places where loop variables are copied (Go 1.22+)
    - sqlclosecheck # checks that sql.Rows and sql.Stmt are closed
    - bodyclose # checks whether HTTP response body is closed successfully
    - unparam # reports unused function parameters
    - unused

  settings:
    staticcheck:
      # SAxxxx checks in https://staticcheck.dev/docs/configuration/options/#checks
      # Example (to disable some checks): [ "all", "-SA1000", "-SA1001"]
      # Default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
      checks:
        # Omit embedded fields from selector expression.
        # https://staticcheck.dev/docs/checks/#QF1008
        ["all", "-ST1000", "-ST1003", "-ST1012", "-ST1020", "-SA1029"]
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      Default: true
      check-type-assertions: false
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      # Such cases aren't reported by default.
      # Default: false
      check-blank: true
      # To disable the errcheck built-in exclude list.
      # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
      # Default: false
      disable-default-exclusions: true
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - github.com/joho/godotenv.Load
        - (*github.com/tarantool/go-tarantool.Connection).Close
        - (*database/sql.DB).Close
        - (*database/sql.Conn).Close
        - (*database/sql.Rows).Close
        - (CloudManager/internal/repository.RepoTx).Rollback
        - (*database/sql.Tx).Rollback
        - (*go.mongodb.org/mongo-driver/mongo.Cursor).Close
        - (*go.mongodb.org/mongo-driver/mongo.Client).Disconnect
        - (*github.com/go-redis/redis/v8.baseClient).Close
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
      # Display function signature instead of selector.
      # Default: false
      verbose: true

issues:
  max-same-issues: 15
