/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainPageMetadata
 */
export interface DomainPageMetadata {
    /**
     * 
     * @type {string}
     * @memberof DomainPageMetadata
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainPageMetadata
     */
    url?: string;
}

/**
 * Check if a given object implements the DomainPageMetadata interface.
 */
export function instanceOfDomainPageMetadata(value: object): value is DomainPageMetadata {
    return true;
}

export function DomainPageMetadataFromJSON(json: any): DomainPageMetadata {
    return DomainPageMetadataFromJSONTyped(json, false);
}

export function DomainPageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPageMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : json['tags'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DomainPageMetadataToJSON(json: any): DomainPageMetadata {
    return DomainPageMetadataToJSONTyped(json, false);
}

export function DomainPageMetadataToJSONTyped(value?: DomainPageMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
        'url': value['url'],
    };
}

