/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainRole } from './DomainRole';
import {
    DomainRoleFromJSON,
    DomainRoleFromJSONTyped,
    DomainRoleToJSON,
    DomainRoleToJSONTyped,
} from './DomainRole';

/**
 * 
 * @export
 * @interface DomainUser
 */
export interface DomainUser {
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    firstName?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    profilePicUrl?: string;
    /**
     * 
     * @type {DomainRole}
     * @memberof DomainUser
     */
    role?: DomainRole;
    /**
     * 
     * @type {string}
     * @memberof DomainUser
     */
    updatedAt?: string;
}



/**
 * Check if a given object implements the DomainUser interface.
 */
export function instanceOfDomainUser(value: object): value is DomainUser {
    return true;
}

export function DomainUserFromJSON(json: any): DomainUser {
    return DomainUserFromJSONTyped(json, false);
}

export function DomainUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainUser {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'profilePicUrl': json['profilePicUrl'] == null ? undefined : json['profilePicUrl'],
        'role': json['role'] == null ? undefined : DomainRoleFromJSON(json['role']),
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function DomainUserToJSON(json: any): DomainUser {
    return DomainUserToJSONTyped(json, false);
}

export function DomainUserToJSONTyped(value?: DomainUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'createdAt': value['createdAt'],
        'email': value['email'],
        'firstName': value['firstName'],
        'id': value['id'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'profilePicUrl': value['profilePicUrl'],
        'role': DomainRoleToJSON(value['role']),
        'updatedAt': value['updatedAt'],
    };
}

