/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainMaterialType = {
    MaterialTypePDF: 'PDF',
    MaterialTypeImage: 'IMAGE',
    MaterialTypeVideo: 'VIDEO',
    MaterialTypeLink: 'LINK',
    MaterialTypeAudio: 'AUDIO'
} as const;
export type DomainMaterialType = typeof DomainMaterialType[keyof typeof DomainMaterialType];


export function instanceOfDomainMaterialType(value: any): boolean {
    for (const key in DomainMaterialType) {
        if (Object.prototype.hasOwnProperty.call(DomainMaterialType, key)) {
            if (DomainMaterialType[key as keyof typeof DomainMaterialType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainMaterialTypeFromJSON(json: any): DomainMaterialType {
    return DomainMaterialTypeFromJSONTyped(json, false);
}

export function DomainMaterialTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainMaterialType {
    return json as DomainMaterialType;
}

export function DomainMaterialTypeToJSON(value?: DomainMaterialType | null): any {
    return value as any;
}

export function DomainMaterialTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainMaterialType {
    return value as DomainMaterialType;
}

