/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainVideo
 */
export interface DomainVideo {
    /**
     * 
     * @type {string}
     * @memberof DomainVideo
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainVideo
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainVideo
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainVideo
     */
    tourId?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainVideo
     */
    url?: string;
}

/**
 * Check if a given object implements the DomainVideo interface.
 */
export function instanceOfDomainVideo(value: object): value is DomainVideo {
    return true;
}

export function DomainVideoFromJSON(json: any): DomainVideo {
    return DomainVideoFromJSONTyped(json, false);
}

export function DomainVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'tourId': json['tourId'] == null ? undefined : json['tourId'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DomainVideoToJSON(json: any): DomainVideo {
    return DomainVideoToJSONTyped(json, false);
}

export function DomainVideoToJSONTyped(value?: DomainVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'tourId': value['tourId'],
        'url': value['url'],
    };
}

