/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainLogin
 */
export interface DomainLogin {
    /**
     * 
     * @type {string}
     * @memberof DomainLogin
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLogin
     */
    password: string;
}

/**
 * Check if a given object implements the DomainLogin interface.
 */
export function instanceOfDomainLogin(value: object): value is DomainLogin {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function DomainLoginFromJSON(json: any): DomainLogin {
    return DomainLoginFromJSONTyped(json, false);
}

export function DomainLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function DomainLoginToJSON(json: any): DomainLogin {
    return DomainLoginToJSONTyped(json, false);
}

export function DomainLoginToJSONTyped(value?: DomainLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

