/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainTourDate
 */
export interface DomainTourDate {
    /**
     * 
     * @type {string}
     * @memberof DomainTourDate
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourDate
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourDate
     */
    groupSize?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainTourDate
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DomainTourDate
     */
    isAvailable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DomainTourDate
     */
    tourId?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourDate
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the DomainTourDate interface.
 */
export function instanceOfDomainTourDate(value: object): value is DomainTourDate {
    return true;
}

export function DomainTourDateFromJSON(json: any): DomainTourDate {
    return DomainTourDateFromJSONTyped(json, false);
}

export function DomainTourDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTourDate {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'date': json['date'] == null ? undefined : json['date'],
        'groupSize': json['groupSize'] == null ? undefined : json['groupSize'],
        'id': json['id'] == null ? undefined : json['id'],
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
        'tourId': json['tourId'] == null ? undefined : json['tourId'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function DomainTourDateToJSON(json: any): DomainTourDate {
    return DomainTourDateToJSONTyped(json, false);
}

export function DomainTourDateToJSONTyped(value?: DomainTourDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'date': value['date'],
        'groupSize': value['groupSize'],
        'id': value['id'],
        'isAvailable': value['isAvailable'],
        'tourId': value['tourId'],
        'updatedAt': value['updatedAt'],
    };
}

