/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainBookingRequest
 */
export interface DomainBookingRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DomainBookingRequest
     */
    isVip?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    lastContactPage?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainBookingRequest
     */
    rooms?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    subscriptionType?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    tourId?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    travelDate?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainBookingRequest
     */
    travelers?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainBookingRequest
     */
    zohoDealId?: string;
}

/**
 * Check if a given object implements the DomainBookingRequest interface.
 */
export function instanceOfDomainBookingRequest(value: object): value is DomainBookingRequest {
    return true;
}

export function DomainBookingRequestFromJSON(json: any): DomainBookingRequest {
    return DomainBookingRequestFromJSONTyped(json, false);
}

export function DomainBookingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainBookingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'isVip': json['isVip'] == null ? undefined : json['isVip'],
        'language': json['language'] == null ? undefined : json['language'],
        'lastContactPage': json['lastContactPage'] == null ? undefined : json['lastContactPage'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'rooms': json['rooms'] == null ? undefined : json['rooms'],
        'subscriptionType': json['subscriptionType'] == null ? undefined : json['subscriptionType'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'tourId': json['tourId'] == null ? undefined : json['tourId'],
        'travelDate': json['travelDate'] == null ? undefined : json['travelDate'],
        'travelers': json['travelers'] == null ? undefined : json['travelers'],
        'zohoDealId': json['zohoDealId'] == null ? undefined : json['zohoDealId'],
    };
}

export function DomainBookingRequestToJSON(json: any): DomainBookingRequest {
    return DomainBookingRequestToJSONTyped(json, false);
}

export function DomainBookingRequestToJSONTyped(value?: DomainBookingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'email': value['email'],
        'id': value['id'],
        'isVip': value['isVip'],
        'language': value['language'],
        'lastContactPage': value['lastContactPage'],
        'name': value['name'],
        'phone': value['phone'],
        'rooms': value['rooms'],
        'subscriptionType': value['subscriptionType'],
        'timezone': value['timezone'],
        'tourId': value['tourId'],
        'travelDate': value['travelDate'],
        'travelers': value['travelers'],
        'zohoDealId': value['zohoDealId'],
    };
}

