/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainCategory
 */
export interface DomainCategory {
    /**
     * 
     * @type {number}
     * @memberof DomainCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainCategory
     */
    name?: string;
}

/**
 * Check if a given object implements the DomainCategory interface.
 */
export function instanceOfDomainCategory(value: object): value is DomainCategory {
    return true;
}

export function DomainCategoryFromJSON(json: any): DomainCategory {
    return DomainCategoryFromJSONTyped(json, false);
}

export function DomainCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DomainCategoryToJSON(json: any): DomainCategory {
    return DomainCategoryToJSONTyped(json, false);
}

export function DomainCategoryToJSONTyped(value?: DomainCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

