/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainDifficultyLevel } from './DomainDifficultyLevel';
import {
    DomainDifficultyLevelFromJSON,
    DomainDifficultyLevelFromJSONTyped,
    DomainDifficultyLevelToJSON,
    DomainDifficultyLevelToJSONTyped,
} from './DomainDifficultyLevel';

/**
 * 
 * @export
 * @interface DomainTour
 */
export interface DomainTour {
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTour
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    ctaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    ctaTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    description?: string;
    /**
     * 
     * @type {DomainDifficultyLevel}
     * @memberof DomainTour
     */
    difficulty?: DomainDifficultyLevel;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    durationDays?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    endLocation?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainTour
     */
    faq?: object;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    groupSize?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DomainTour
     */
    isShowRooms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainTour
     */
    isShowVip?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTour
     */
    languages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    minAge?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp1Description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp1ImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp1Title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp2Description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp2ImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    popUp2Title?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainTour
     */
    program?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    reviewsSectionName?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    roomPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    spotsLeft?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    startLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    subtitle?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    vipPrice?: number;
}



/**
 * Check if a given object implements the DomainTour interface.
 */
export function instanceOfDomainTour(value: object): value is DomainTour {
    return true;
}

export function DomainTourFromJSON(json: any): DomainTour {
    return DomainTourFromJSONTyped(json, false);
}

export function DomainTourFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTour {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'ctaDescription': json['ctaDescription'] == null ? undefined : json['ctaDescription'],
        'ctaTitle': json['ctaTitle'] == null ? undefined : json['ctaTitle'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : DomainDifficultyLevelFromJSON(json['difficulty']),
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'faq': json['faq'] == null ? undefined : json['faq'],
        'groupSize': json['groupSize'] == null ? undefined : json['groupSize'],
        'id': json['id'] == null ? undefined : json['id'],
        'isShowRooms': json['isShowRooms'] == null ? undefined : json['isShowRooms'],
        'isShowVip': json['isShowVip'] == null ? undefined : json['isShowVip'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'location': json['location'] == null ? undefined : json['location'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'popUp1Description': json['popUp1Description'] == null ? undefined : json['popUp1Description'],
        'popUp1ImageUrl': json['popUp1ImageUrl'] == null ? undefined : json['popUp1ImageUrl'],
        'popUp1Title': json['popUp1Title'] == null ? undefined : json['popUp1Title'],
        'popUp2Description': json['popUp2Description'] == null ? undefined : json['popUp2Description'],
        'popUp2ImageUrl': json['popUp2ImageUrl'] == null ? undefined : json['popUp2ImageUrl'],
        'popUp2Title': json['popUp2Title'] == null ? undefined : json['popUp2Title'],
        'program': json['program'] == null ? undefined : json['program'],
        'reviewsSectionName': json['reviewsSectionName'] == null ? undefined : json['reviewsSectionName'],
        'roomPrice': json['roomPrice'] == null ? undefined : json['roomPrice'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'spotsLeft': json['spotsLeft'] == null ? undefined : json['spotsLeft'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'vipPrice': json['vipPrice'] == null ? undefined : json['vipPrice'],
    };
}

export function DomainTourToJSON(json: any): DomainTour {
    return DomainTourToJSONTyped(json, false);
}

export function DomainTourToJSONTyped(value?: DomainTour | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMonths': value['availableMonths'],
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'],
        'ctaDescription': value['ctaDescription'],
        'ctaTitle': value['ctaTitle'],
        'description': value['description'],
        'difficulty': DomainDifficultyLevelToJSON(value['difficulty']),
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'faq': value['faq'],
        'groupSize': value['groupSize'],
        'id': value['id'],
        'isShowRooms': value['isShowRooms'],
        'isShowVip': value['isShowVip'],
        'languages': value['languages'],
        'location': value['location'],
        'minAge': value['minAge'],
        'popUp1Description': value['popUp1Description'],
        'popUp1ImageUrl': value['popUp1ImageUrl'],
        'popUp1Title': value['popUp1Title'],
        'popUp2Description': value['popUp2Description'],
        'popUp2ImageUrl': value['popUp2ImageUrl'],
        'popUp2Title': value['popUp2Title'],
        'program': value['program'],
        'reviewsSectionName': value['reviewsSectionName'],
        'roomPrice': value['roomPrice'],
        'slug': value['slug'],
        'spotsLeft': value['spotsLeft'],
        'startLocation': value['startLocation'],
        'subtitle': value['subtitle'],
        'title': value['title'],
        'updatedAt': value['updatedAt'],
        'vipPrice': value['vipPrice'],
    };
}

