/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainRole = {
    RoleAdmin: 'ADMIN',
    RoleClient: 'CLIENT',
    RoleGuide: 'GUIDE'
} as const;
export type DomainRole = typeof DomainRole[keyof typeof DomainRole];


export function instanceOfDomainRole(value: any): boolean {
    for (const key in DomainRole) {
        if (Object.prototype.hasOwnProperty.call(DomainRole, key)) {
            if (DomainRole[key as keyof typeof DomainRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainRoleFromJSON(json: any): DomainRole {
    return DomainRoleFromJSONTyped(json, false);
}

export function DomainRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainRole {
    return json as DomainRole;
}

export function DomainRoleToJSON(value?: DomainRole | null): any {
    return value as any;
}

export function DomainRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainRole {
    return value as DomainRole;
}

