/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainMaterialType } from './DomainMaterialType';
import {
    DomainMaterialTypeFromJSON,
    DomainMaterialTypeFromJSONTyped,
    DomainMaterialTypeToJSON,
    DomainMaterialTypeToJSONTyped,
} from './DomainMaterialType';

/**
 * 
 * @export
 * @interface DomainTourMaterial
 */
export interface DomainTourMaterial {
    /**
     * 
     * @type {string}
     * @memberof DomainTourMaterial
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourMaterial
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourMaterial
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourMaterial
     */
    tourId?: number;
    /**
     * 
     * @type {DomainMaterialType}
     * @memberof DomainTourMaterial
     */
    type?: DomainMaterialType;
    /**
     * 
     * @type {string}
     * @memberof DomainTourMaterial
     */
    url?: string;
}



/**
 * Check if a given object implements the DomainTourMaterial interface.
 */
export function instanceOfDomainTourMaterial(value: object): value is DomainTourMaterial {
    return true;
}

export function DomainTourMaterialFromJSON(json: any): DomainTourMaterial {
    return DomainTourMaterialFromJSONTyped(json, false);
}

export function DomainTourMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTourMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'tourId': json['tourId'] == null ? undefined : json['tourId'],
        'type': json['type'] == null ? undefined : DomainMaterialTypeFromJSON(json['type']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DomainTourMaterialToJSON(json: any): DomainTourMaterial {
    return DomainTourMaterialToJSONTyped(json, false);
}

export function DomainTourMaterialToJSONTyped(value?: DomainTourMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'id': value['id'],
        'title': value['title'],
        'tourId': value['tourId'],
        'type': DomainMaterialTypeToJSON(value['type']),
        'url': value['url'],
    };
}

