/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainReview
 */
export interface DomainReview {
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    link?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainReview
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    tourId?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainReview
     */
    userName?: string;
}

/**
 * Check if a given object implements the DomainReview interface.
 */
export function instanceOfDomainReview(value: object): value is DomainReview {
    return true;
}

export function DomainReviewFromJSON(json: any): DomainReview {
    return DomainReviewFromJSONTyped(json, false);
}

export function DomainReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainReview {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'link': json['link'] == null ? undefined : json['link'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'tourId': json['tourId'] == null ? undefined : json['tourId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
    };
}

export function DomainReviewToJSON(json: any): DomainReview {
    return DomainReviewToJSONTyped(json, false);
}

export function DomainReviewToJSONTyped(value?: DomainReview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'image': value['image'],
        'link': value['link'],
        'rating': value['rating'],
        'tourId': value['tourId'],
        'userId': value['userId'],
        'userName': value['userName'],
    };
}

