/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainActivity
 */
export interface DomainActivity {
    /**
     * 
     * @type {string}
     * @memberof DomainActivity
     */
    activity?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainActivity
     */
    iconName?: string;
}

/**
 * Check if a given object implements the DomainActivity interface.
 */
export function instanceOfDomainActivity(value: object): value is DomainActivity {
    return true;
}

export function DomainActivityFromJSON(json: any): DomainActivity {
    return DomainActivityFromJSONTyped(json, false);
}

export function DomainActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'activity': json['activity'] == null ? undefined : json['activity'],
        'iconName': json['iconName'] == null ? undefined : json['iconName'],
    };
}

export function DomainActivityToJSON(json: any): DomainActivity {
    return DomainActivityToJSONTyped(json, false);
}

export function DomainActivityToJSONTyped(value?: DomainActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity': value['activity'],
        'iconName': value['iconName'],
    };
}

