/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainActivity } from './DomainActivity';
import {
    DomainActivityFromJSON,
    DomainActivityFromJSONTyped,
    DomainActivityToJSON,
    DomainActivityToJSONTyped,
} from './DomainActivity';
import type { DomainReview } from './DomainReview';
import {
    DomainReviewFromJSON,
    DomainReviewFromJSONTyped,
    DomainReviewToJSON,
    DomainReviewToJSONTyped,
} from './DomainReview';
import type { DomainTourDate } from './DomainTourDate';
import {
    DomainTourDateFromJSON,
    DomainTourDateFromJSONTyped,
    DomainTourDateToJSON,
    DomainTourDateToJSONTyped,
} from './DomainTourDate';
import type { DomainPhoto } from './DomainPhoto';
import {
    DomainPhotoFromJSON,
    DomainPhotoFromJSONTyped,
    DomainPhotoToJSON,
    DomainPhotoToJSONTyped,
} from './DomainPhoto';
import type { DomainDifficultyLevel } from './DomainDifficultyLevel';
import {
    DomainDifficultyLevelFromJSON,
    DomainDifficultyLevelFromJSONTyped,
    DomainDifficultyLevelToJSON,
    DomainDifficultyLevelToJSONTyped,
} from './DomainDifficultyLevel';

/**
 * 
 * @export
 * @interface DomainTourFull
 */
export interface DomainTourFull {
    /**
     * 
     * @type {Array<DomainActivity>}
     * @memberof DomainTourFull
     */
    activities?: Array<DomainActivity>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    ctaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    ctaTitle?: string;
    /**
     * 
     * @type {Array<DomainTourDate>}
     * @memberof DomainTourFull
     */
    dates?: Array<DomainTourDate>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    description?: string;
    /**
     * 
     * @type {DomainDifficultyLevel}
     * @memberof DomainTourFull
     */
    difficulty?: DomainDifficultyLevel;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    durationDays?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    endLocation?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainTourFull
     */
    faq?: object;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    groupSize?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    included?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DomainTourFull
     */
    isShowRooms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainTourFull
     */
    isShowVip?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    languages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    minAge?: number;
    /**
     * 
     * @type {Array<DomainPhoto>}
     * @memberof DomainTourFull
     */
    photos?: Array<DomainPhoto>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp1Description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp1ImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp1Title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp2Description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp2ImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    popUp2Title?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainTourFull
     */
    program?: object;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    reviewAmount?: number;
    /**
     * 
     * @type {Array<DomainReview>}
     * @memberof DomainTourFull
     */
    reviews?: Array<DomainReview>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    reviewsSectionName?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    roomPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    spotsLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    starAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    startLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    subtitle?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    summary?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    vipPrice?: number;
}



/**
 * Check if a given object implements the DomainTourFull interface.
 */
export function instanceOfDomainTourFull(value: object): value is DomainTourFull {
    return true;
}

export function DomainTourFullFromJSON(json: any): DomainTourFull {
    return DomainTourFullFromJSONTyped(json, false);
}

export function DomainTourFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTourFull {
    if (json == null) {
        return json;
    }
    return {
        
        'activities': json['activities'] == null ? undefined : ((json['activities'] as Array<any>).map(DomainActivityFromJSON)),
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'ctaDescription': json['ctaDescription'] == null ? undefined : json['ctaDescription'],
        'ctaTitle': json['ctaTitle'] == null ? undefined : json['ctaTitle'],
        'dates': json['dates'] == null ? undefined : ((json['dates'] as Array<any>).map(DomainTourDateFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : DomainDifficultyLevelFromJSON(json['difficulty']),
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'faq': json['faq'] == null ? undefined : json['faq'],
        'groupSize': json['groupSize'] == null ? undefined : json['groupSize'],
        'id': json['id'] == null ? undefined : json['id'],
        'included': json['included'] == null ? undefined : json['included'],
        'isShowRooms': json['isShowRooms'] == null ? undefined : json['isShowRooms'],
        'isShowVip': json['isShowVip'] == null ? undefined : json['isShowVip'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'location': json['location'] == null ? undefined : json['location'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'photos': json['photos'] == null ? undefined : ((json['photos'] as Array<any>).map(DomainPhotoFromJSON)),
        'popUp1Description': json['popUp1Description'] == null ? undefined : json['popUp1Description'],
        'popUp1ImageUrl': json['popUp1ImageUrl'] == null ? undefined : json['popUp1ImageUrl'],
        'popUp1Title': json['popUp1Title'] == null ? undefined : json['popUp1Title'],
        'popUp2Description': json['popUp2Description'] == null ? undefined : json['popUp2Description'],
        'popUp2ImageUrl': json['popUp2ImageUrl'] == null ? undefined : json['popUp2ImageUrl'],
        'popUp2Title': json['popUp2Title'] == null ? undefined : json['popUp2Title'],
        'program': json['program'] == null ? undefined : json['program'],
        'reviewAmount': json['reviewAmount'] == null ? undefined : json['reviewAmount'],
        'reviews': json['reviews'] == null ? undefined : ((json['reviews'] as Array<any>).map(DomainReviewFromJSON)),
        'reviewsSectionName': json['reviewsSectionName'] == null ? undefined : json['reviewsSectionName'],
        'roomPrice': json['roomPrice'] == null ? undefined : json['roomPrice'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'spotsLeft': json['spotsLeft'] == null ? undefined : json['spotsLeft'],
        'starAmount': json['starAmount'] == null ? undefined : json['starAmount'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'vipPrice': json['vipPrice'] == null ? undefined : json['vipPrice'],
    };
}

export function DomainTourFullToJSON(json: any): DomainTourFull {
    return DomainTourFullToJSONTyped(json, false);
}

export function DomainTourFullToJSONTyped(value?: DomainTourFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activities': value['activities'] == null ? undefined : ((value['activities'] as Array<any>).map(DomainActivityToJSON)),
        'availableMonths': value['availableMonths'],
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'],
        'ctaDescription': value['ctaDescription'],
        'ctaTitle': value['ctaTitle'],
        'dates': value['dates'] == null ? undefined : ((value['dates'] as Array<any>).map(DomainTourDateToJSON)),
        'description': value['description'],
        'difficulty': DomainDifficultyLevelToJSON(value['difficulty']),
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'faq': value['faq'],
        'groupSize': value['groupSize'],
        'id': value['id'],
        'included': value['included'],
        'isShowRooms': value['isShowRooms'],
        'isShowVip': value['isShowVip'],
        'languages': value['languages'],
        'location': value['location'],
        'minAge': value['minAge'],
        'photos': value['photos'] == null ? undefined : ((value['photos'] as Array<any>).map(DomainPhotoToJSON)),
        'popUp1Description': value['popUp1Description'],
        'popUp1ImageUrl': value['popUp1ImageUrl'],
        'popUp1Title': value['popUp1Title'],
        'popUp2Description': value['popUp2Description'],
        'popUp2ImageUrl': value['popUp2ImageUrl'],
        'popUp2Title': value['popUp2Title'],
        'program': value['program'],
        'reviewAmount': value['reviewAmount'],
        'reviews': value['reviews'] == null ? undefined : ((value['reviews'] as Array<any>).map(DomainReviewToJSON)),
        'reviewsSectionName': value['reviewsSectionName'],
        'roomPrice': value['roomPrice'],
        'slug': value['slug'],
        'spotsLeft': value['spotsLeft'],
        'starAmount': value['starAmount'],
        'startLocation': value['startLocation'],
        'subtitle': value['subtitle'],
        'summary': value['summary'],
        'title': value['title'],
        'updatedAt': value['updatedAt'],
        'vipPrice': value['vipPrice'],
    };
}

