/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainTag
 */
export interface DomainTag {
    /**
     * 
     * @type {number}
     * @memberof DomainTag
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTag
     */
    name?: string;
}

/**
 * Check if a given object implements the DomainTag interface.
 */
export function instanceOfDomainTag(value: object): value is DomainTag {
    return true;
}

export function DomainTagFromJSON(json: any): DomainTag {
    return DomainTagFromJSONTyped(json, false);
}

export function DomainTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DomainTagToJSON(json: any): DomainTag {
    return DomainTagToJSONTyped(json, false);
}

export function DomainTagToJSONTyped(value?: DomainTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

