/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainDifficultyLevel = {
    DifficultyLevelEASY: 'EASY',
    DifficultyLevelMEDIUM: 'MEDIUM',
    DifficultyLevelHARD: 'HARD'
} as const;
export type DomainDifficultyLevel = typeof DomainDifficultyLevel[keyof typeof DomainDifficultyLevel];


export function instanceOfDomainDifficultyLevel(value: any): boolean {
    for (const key in DomainDifficultyLevel) {
        if (Object.prototype.hasOwnProperty.call(DomainDifficultyLevel, key)) {
            if (DomainDifficultyLevel[key as keyof typeof DomainDifficultyLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainDifficultyLevelFromJSON(json: any): DomainDifficultyLevel {
    return DomainDifficultyLevelFromJSONTyped(json, false);
}

export function DomainDifficultyLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDifficultyLevel {
    return json as DomainDifficultyLevel;
}

export function DomainDifficultyLevelToJSON(value?: DomainDifficultyLevel | null): any {
    return value as any;
}

export function DomainDifficultyLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainDifficultyLevel {
    return value as DomainDifficultyLevel;
}

