/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainRegister
 */
export interface DomainRegister {
    /**
     * 
     * @type {string}
     * @memberof DomainRegister
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DomainRegister
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof DomainRegister
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof DomainRegister
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof DomainRegister
     */
    phone?: string;
}

/**
 * Check if a given object implements the DomainRegister interface.
 */
export function instanceOfDomainRegister(value: object): value is DomainRegister {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function DomainRegisterFromJSON(json: any): DomainRegister {
    return DomainRegisterFromJSONTyped(json, false);
}

export function DomainRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainRegister {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'password': json['password'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function DomainRegisterToJSON(json: any): DomainRegister {
    return DomainRegisterToJSONTyped(json, false);
}

export function DomainRegisterToJSONTyped(value?: DomainRegister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'password': value['password'],
        'phone': value['phone'],
    };
}

