/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainTourDate } from './DomainTourDate';
import {
    DomainTourDateFromJSON,
    DomainTourDateFromJSONTyped,
    DomainTourDateToJSON,
    DomainTourDateToJSONTyped,
} from './DomainTourDate';
import type { DomainTourMaterial } from './DomainTourMaterial';
import {
    DomainTourMaterialFromJSON,
    DomainTourMaterialFromJSONTyped,
    DomainTourMaterialToJSON,
    DomainTourMaterialToJSONTyped,
} from './DomainTourMaterial';
import type { DomainPhoto } from './DomainPhoto';
import {
    DomainPhotoFromJSON,
    DomainPhotoFromJSONTyped,
    DomainPhotoToJSON,
    DomainPhotoToJSONTyped,
} from './DomainPhoto';
import type { DomainGuide } from './DomainGuide';
import {
    DomainGuideFromJSON,
    DomainGuideFromJSONTyped,
    DomainGuideToJSON,
    DomainGuideToJSONTyped,
} from './DomainGuide';
import type { DomainCategory } from './DomainCategory';
import {
    DomainCategoryFromJSON,
    DomainCategoryFromJSONTyped,
    DomainCategoryToJSON,
    DomainCategoryToJSONTyped,
} from './DomainCategory';
import type { DomainVideo } from './DomainVideo';
import {
    DomainVideoFromJSON,
    DomainVideoFromJSONTyped,
    DomainVideoToJSON,
    DomainVideoToJSONTyped,
} from './DomainVideo';
import type { DomainTag } from './DomainTag';
import {
    DomainTagFromJSON,
    DomainTagFromJSONTyped,
    DomainTagToJSON,
    DomainTagToJSONTyped,
} from './DomainTag';
import type { DomainDifficultyLevel } from './DomainDifficultyLevel';
import {
    DomainDifficultyLevelFromJSON,
    DomainDifficultyLevelFromJSONTyped,
    DomainDifficultyLevelToJSON,
    DomainDifficultyLevelToJSONTyped,
} from './DomainDifficultyLevel';

/**
 * 
 * @export
 * @interface DomainTourFull
 */
export interface DomainTourFull {
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {Array<DomainCategory>}
     * @memberof DomainTourFull
     */
    categories?: Array<DomainCategory>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<DomainTourDate>}
     * @memberof DomainTourFull
     */
    dates?: Array<DomainTourDate>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    description?: string;
    /**
     * 
     * @type {DomainDifficultyLevel}
     * @memberof DomainTourFull
     */
    difficulty?: DomainDifficultyLevel;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    durationDays?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    endLocation?: string;
    /**
     * 
     * @type {DomainGuide}
     * @memberof DomainTourFull
     */
    guide?: DomainGuide;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    guideId?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    id?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTourFull
     */
    languages?: Array<string>;
    /**
     * 
     * @type {Array<DomainTourMaterial>}
     * @memberof DomainTourFull
     */
    materials?: Array<DomainTourMaterial>;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    minAge?: number;
    /**
     * 
     * @type {Array<DomainPhoto>}
     * @memberof DomainTourFull
     */
    photos?: Array<DomainPhoto>;
    /**
     * 
     * @type {number}
     * @memberof DomainTourFull
     */
    price?: number;
    /**
     * 
     * @type {object}
     * @memberof DomainTourFull
     */
    program?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    startLocation?: string;
    /**
     * 
     * @type {Array<DomainTag>}
     * @memberof DomainTourFull
     */
    tags?: Array<DomainTag>;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTourFull
     */
    updatedAt?: string;
    /**
     * 
     * @type {Array<DomainVideo>}
     * @memberof DomainTourFull
     */
    videos?: Array<DomainVideo>;
}



/**
 * Check if a given object implements the DomainTourFull interface.
 */
export function instanceOfDomainTourFull(value: object): value is DomainTourFull {
    return true;
}

export function DomainTourFullFromJSON(json: any): DomainTourFull {
    return DomainTourFullFromJSONTyped(json, false);
}

export function DomainTourFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTourFull {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(DomainCategoryFromJSON)),
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'dates': json['dates'] == null ? undefined : ((json['dates'] as Array<any>).map(DomainTourDateFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : DomainDifficultyLevelFromJSON(json['difficulty']),
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'guide': json['guide'] == null ? undefined : DomainGuideFromJSON(json['guide']),
        'guideId': json['guideId'] == null ? undefined : json['guideId'],
        'id': json['id'] == null ? undefined : json['id'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'materials': json['materials'] == null ? undefined : ((json['materials'] as Array<any>).map(DomainTourMaterialFromJSON)),
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'photos': json['photos'] == null ? undefined : ((json['photos'] as Array<any>).map(DomainPhotoFromJSON)),
        'price': json['price'] == null ? undefined : json['price'],
        'program': json['program'] == null ? undefined : json['program'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(DomainTagFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(DomainVideoFromJSON)),
    };
}

export function DomainTourFullToJSON(json: any): DomainTourFull {
    return DomainTourFullToJSONTyped(json, false);
}

export function DomainTourFullToJSONTyped(value?: DomainTourFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMonths': value['availableMonths'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(DomainCategoryToJSON)),
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'],
        'dates': value['dates'] == null ? undefined : ((value['dates'] as Array<any>).map(DomainTourDateToJSON)),
        'description': value['description'],
        'difficulty': DomainDifficultyLevelToJSON(value['difficulty']),
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'guide': DomainGuideToJSON(value['guide']),
        'guideId': value['guideId'],
        'id': value['id'],
        'languages': value['languages'],
        'materials': value['materials'] == null ? undefined : ((value['materials'] as Array<any>).map(DomainTourMaterialToJSON)),
        'minAge': value['minAge'],
        'photos': value['photos'] == null ? undefined : ((value['photos'] as Array<any>).map(DomainPhotoToJSON)),
        'price': value['price'],
        'program': value['program'],
        'slug': value['slug'],
        'startLocation': value['startLocation'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(DomainTagToJSON)),
        'title': value['title'],
        'updatedAt': value['updatedAt'],
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(DomainVideoToJSON)),
    };
}

