/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainDifficultyLevel } from './DomainDifficultyLevel';
import {
    DomainDifficultyLevelFromJSON,
    DomainDifficultyLevelFromJSONTyped,
    DomainDifficultyLevelToJSON,
    DomainDifficultyLevelToJSONTyped,
} from './DomainDifficultyLevel';

/**
 * 
 * @export
 * @interface DomainTour
 */
export interface DomainTour {
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTour
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    description?: string;
    /**
     * 
     * @type {DomainDifficultyLevel}
     * @memberof DomainTour
     */
    difficulty?: DomainDifficultyLevel;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    durationDays?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    endLocation?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    guideId?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    id?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainTour
     */
    languages?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    minAge?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainTour
     */
    price?: number;
    /**
     * 
     * @type {object}
     * @memberof DomainTour
     */
    program?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    startLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainTour
     */
    updatedAt?: string;
}



/**
 * Check if a given object implements the DomainTour interface.
 */
export function instanceOfDomainTour(value: object): value is DomainTour {
    return true;
}

export function DomainTourFromJSON(json: any): DomainTour {
    return DomainTourFromJSONTyped(json, false);
}

export function DomainTourFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainTour {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : DomainDifficultyLevelFromJSON(json['difficulty']),
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'guideId': json['guideId'] == null ? undefined : json['guideId'],
        'id': json['id'] == null ? undefined : json['id'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'price': json['price'] == null ? undefined : json['price'],
        'program': json['program'] == null ? undefined : json['program'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function DomainTourToJSON(json: any): DomainTour {
    return DomainTourToJSONTyped(json, false);
}

export function DomainTourToJSONTyped(value?: DomainTour | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMonths': value['availableMonths'],
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'],
        'description': value['description'],
        'difficulty': DomainDifficultyLevelToJSON(value['difficulty']),
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'guideId': value['guideId'],
        'id': value['id'],
        'languages': value['languages'],
        'minAge': value['minAge'],
        'price': value['price'],
        'program': value['program'],
        'slug': value['slug'],
        'startLocation': value['startLocation'],
        'title': value['title'],
        'updatedAt': value['updatedAt'],
    };
}

