/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainUser } from './DomainUser';
import {
    DomainUserFromJSON,
    DomainUserFromJSONTyped,
    DomainUserToJSON,
    DomainUserToJSONTyped,
} from './DomainUser';

/**
 * 
 * @export
 * @interface DomainGuide
 */
export interface DomainGuide {
    /**
     * 
     * @type {string}
     * @memberof DomainGuide
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainGuide
     */
    experience?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainGuide
     */
    id?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainGuide
     */
    specializations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DomainGuide
     */
    updatedAt?: string;
    /**
     * 
     * @type {DomainUser}
     * @memberof DomainGuide
     */
    user?: DomainUser;
    /**
     * 
     * @type {number}
     * @memberof DomainGuide
     */
    userId?: number;
}

/**
 * Check if a given object implements the DomainGuide interface.
 */
export function instanceOfDomainGuide(value: object): value is DomainGuide {
    return true;
}

export function DomainGuideFromJSON(json: any): DomainGuide {
    return DomainGuideFromJSONTyped(json, false);
}

export function DomainGuideFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainGuide {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'experience': json['experience'] == null ? undefined : json['experience'],
        'id': json['id'] == null ? undefined : json['id'],
        'specializations': json['specializations'] == null ? undefined : json['specializations'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'user': json['user'] == null ? undefined : DomainUserFromJSON(json['user']),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function DomainGuideToJSON(json: any): DomainGuide {
    return DomainGuideToJSONTyped(json, false);
}

export function DomainGuideToJSONTyped(value?: DomainGuide | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'experience': value['experience'],
        'id': value['id'],
        'specializations': value['specializations'],
        'updatedAt': value['updatedAt'],
        'user': DomainUserToJSON(value['user']),
        'userId': value['userId'],
    };
}

