/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoArticleSummaryDTO
 */
export interface DtoArticleSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    alt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    excerpt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DtoArticleSummaryDTO
     */
    featured?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleSummaryDTO
     */
    title?: string;
}

/**
 * Check if a given object implements the DtoArticleSummaryDTO interface.
 */
export function instanceOfDtoArticleSummaryDTO(value: object): value is DtoArticleSummaryDTO {
    return true;
}

export function DtoArticleSummaryDTOFromJSON(json: any): DtoArticleSummaryDTO {
    return DtoArticleSummaryDTOFromJSONTyped(json, false);
}

export function DtoArticleSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoArticleSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'alt': json['alt'] == null ? undefined : json['alt'],
        'author': json['author'] == null ? undefined : json['author'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function DtoArticleSummaryDTOToJSON(json: any): DtoArticleSummaryDTO {
    return DtoArticleSummaryDTOToJSONTyped(json, false);
}

export function DtoArticleSummaryDTOToJSONTyped(value?: DtoArticleSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alt': value['alt'],
        'author': value['author'],
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'],
        'excerpt': value['excerpt'],
        'featured': value['featured'],
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
    };
}

