/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoUserDTO } from './DtoUserDTO';
import {
    DtoUserDTOFromJSON,
    DtoUserDTOFromJSONTyped,
    DtoUserDTOToJSON,
    DtoUserDTOToJSONTyped,
} from './DtoUserDTO';

/**
 * 
 * @export
 * @interface DtoAuthResponse
 */
export interface DtoAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoAuthResponse
     */
    token?: string;
    /**
     * 
     * @type {DtoUserDTO}
     * @memberof DtoAuthResponse
     */
    user?: DtoUserDTO;
}

/**
 * Check if a given object implements the DtoAuthResponse interface.
 */
export function instanceOfDtoAuthResponse(value: object): value is DtoAuthResponse {
    return true;
}

export function DtoAuthResponseFromJSON(json: any): DtoAuthResponse {
    return DtoAuthResponseFromJSONTyped(json, false);
}

export function DtoAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'user': json['user'] == null ? undefined : DtoUserDTOFromJSON(json['user']),
    };
}

export function DtoAuthResponseToJSON(json: any): DtoAuthResponse {
    return DtoAuthResponseToJSONTyped(json, false);
}

export function DtoAuthResponseToJSONTyped(value?: DtoAuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'user': DtoUserDTOToJSON(value['user']),
    };
}

