/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoArticleBlockDTO
 */
export interface DtoArticleBlockDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoArticleBlockDTO
     */
    alt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleBlockDTO
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleBlockDTO
     */
    src?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleBlockDTO
     */
    type?: string;
}

/**
 * Check if a given object implements the DtoArticleBlockDTO interface.
 */
export function instanceOfDtoArticleBlockDTO(value: object): value is DtoArticleBlockDTO {
    return true;
}

export function DtoArticleBlockDTOFromJSON(json: any): DtoArticleBlockDTO {
    return DtoArticleBlockDTOFromJSONTyped(json, false);
}

export function DtoArticleBlockDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoArticleBlockDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'alt': json['alt'] == null ? undefined : json['alt'],
        'content': json['content'] == null ? undefined : json['content'],
        'src': json['src'] == null ? undefined : json['src'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function DtoArticleBlockDTOToJSON(json: any): DtoArticleBlockDTO {
    return DtoArticleBlockDTOToJSONTyped(json, false);
}

export function DtoArticleBlockDTOToJSONTyped(value?: DtoArticleBlockDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alt': value['alt'],
        'content': value['content'],
        'src': value['src'],
        'type': value['type'],
    };
}

