/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoArticleDetailDTO
 */
export interface DtoArticleDetailDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    alt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    excerpt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DtoArticleDetailDTO
     */
    featured?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DtoArticleDetailDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    publishedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoArticleDetailDTO
     */
    title?: string;
}

/**
 * Check if a given object implements the DtoArticleDetailDTO interface.
 */
export function instanceOfDtoArticleDetailDTO(value: object): value is DtoArticleDetailDTO {
    return true;
}

export function DtoArticleDetailDTOFromJSON(json: any): DtoArticleDetailDTO {
    return DtoArticleDetailDTOFromJSONTyped(json, false);
}

export function DtoArticleDetailDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoArticleDetailDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'alt': json['alt'] == null ? undefined : json['alt'],
        'author': json['author'] == null ? undefined : json['author'],
        'content': json['content'] == null ? undefined : json['content'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'id': json['id'] == null ? undefined : json['id'],
        'publishedAt': json['publishedAt'] == null ? undefined : json['publishedAt'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function DtoArticleDetailDTOToJSON(json: any): DtoArticleDetailDTO {
    return DtoArticleDetailDTOToJSONTyped(json, false);
}

export function DtoArticleDetailDTOToJSONTyped(value?: DtoArticleDetailDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alt': value['alt'],
        'author': value['author'],
        'content': value['content'],
        'coverUrl': value['coverUrl'],
        'excerpt': value['excerpt'],
        'featured': value['featured'],
        'id': value['id'],
        'publishedAt': value['publishedAt'],
        'slug': value['slug'],
        'title': value['title'],
    };
}

