/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateBookingResponse
 */
export interface DtoCreateBookingResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBookingResponse
     */
    redirectUrl?: string;
}

/**
 * Check if a given object implements the DtoCreateBookingResponse interface.
 */
export function instanceOfDtoCreateBookingResponse(value: object): value is DtoCreateBookingResponse {
    return true;
}

export function DtoCreateBookingResponseFromJSON(json: any): DtoCreateBookingResponse {
    return DtoCreateBookingResponseFromJSONTyped(json, false);
}

export function DtoCreateBookingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateBookingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
    };
}

export function DtoCreateBookingResponseToJSON(json: any): DtoCreateBookingResponse {
    return DtoCreateBookingResponseToJSONTyped(json, false);
}

export function DtoCreateBookingResponseToJSONTyped(value?: DtoCreateBookingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirectUrl': value['redirectUrl'],
    };
}

