/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoContactMeRequest
 */
export interface DtoContactMeRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    lastContactPage?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the DtoContactMeRequest interface.
 */
export function instanceOfDtoContactMeRequest(value: object): value is DtoContactMeRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function DtoContactMeRequestFromJSON(json: any): DtoContactMeRequest {
    return DtoContactMeRequestFromJSONTyped(json, false);
}

export function DtoContactMeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoContactMeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'language': json['language'] == null ? undefined : json['language'],
        'lastContactPage': json['lastContactPage'] == null ? undefined : json['lastContactPage'],
        'name': json['name'],
        'phone': json['phone'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function DtoContactMeRequestToJSON(json: any): DtoContactMeRequest {
    return DtoContactMeRequestToJSONTyped(json, false);
}

export function DtoContactMeRequestToJSONTyped(value?: DtoContactMeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'language': value['language'],
        'lastContactPage': value['lastContactPage'],
        'name': value['name'],
        'phone': value['phone'],
        'timezone': value['timezone'],
    };
}

