/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateTourRequest
 */
export interface DtoCreateTourRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoCreateTourRequest
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    difficulty: string;
    /**
     * 
     * @type {number}
     * @memberof DtoCreateTourRequest
     */
    durationDays?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    endLocation?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoCreateTourRequest
     */
    guideId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoCreateTourRequest
     */
    languages?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DtoCreateTourRequest
     */
    minAge?: number;
    /**
     * 
     * @type {number}
     * @memberof DtoCreateTourRequest
     */
    price?: number;
    /**
     * 
     * @type {object}
     * @memberof DtoCreateTourRequest
     */
    program?: object;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    startLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateTourRequest
     */
    title: string;
}

/**
 * Check if a given object implements the DtoCreateTourRequest interface.
 */
export function instanceOfDtoCreateTourRequest(value: object): value is DtoCreateTourRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DtoCreateTourRequestFromJSON(json: any): DtoCreateTourRequest {
    return DtoCreateTourRequestFromJSONTyped(json, false);
}

export function DtoCreateTourRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateTourRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'description': json['description'],
        'difficulty': json['difficulty'],
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'guideId': json['guideId'] == null ? undefined : json['guideId'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'price': json['price'] == null ? undefined : json['price'],
        'program': json['program'] == null ? undefined : json['program'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'title': json['title'],
    };
}

export function DtoCreateTourRequestToJSON(json: any): DtoCreateTourRequest {
    return DtoCreateTourRequestToJSONTyped(json, false);
}

export function DtoCreateTourRequestToJSONTyped(value?: DtoCreateTourRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMonths': value['availableMonths'],
        'coverUrl': value['coverUrl'],
        'description': value['description'],
        'difficulty': value['difficulty'],
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'guideId': value['guideId'],
        'languages': value['languages'],
        'minAge': value['minAge'],
        'price': value['price'],
        'program': value['program'],
        'slug': value['slug'],
        'startLocation': value['startLocation'],
        'title': value['title'],
    };
}

