/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoChangePasswordDTO
 */
export interface DtoChangePasswordDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoChangePasswordDTO
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof DtoChangePasswordDTO
     */
    newPassword: string;
}

/**
 * Check if a given object implements the DtoChangePasswordDTO interface.
 */
export function instanceOfDtoChangePasswordDTO(value: object): value is DtoChangePasswordDTO {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function DtoChangePasswordDTOFromJSON(json: any): DtoChangePasswordDTO {
    return DtoChangePasswordDTOFromJSONTyped(json, false);
}

export function DtoChangePasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoChangePasswordDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function DtoChangePasswordDTOToJSON(json: any): DtoChangePasswordDTO {
    return DtoChangePasswordDTOToJSONTyped(json, false);
}

export function DtoChangePasswordDTOToJSONTyped(value?: DtoChangePasswordDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

