/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoContactMeResponse
 */
export interface DtoContactMeResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoContactMeResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the DtoContactMeResponse interface.
 */
export function instanceOfDtoContactMeResponse(value: object): value is DtoContactMeResponse {
    return true;
}

export function DtoContactMeResponseFromJSON(json: any): DtoContactMeResponse {
    return DtoContactMeResponseFromJSONTyped(json, false);
}

export function DtoContactMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoContactMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DtoContactMeResponseToJSON(json: any): DtoContactMeResponse {
    return DtoContactMeResponseToJSONTyped(json, false);
}

export function DtoContactMeResponseToJSONTyped(value?: DtoContactMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

