/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoPublicProfileDTO
 */
export interface DtoPublicProfileDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoPublicProfileDTO
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPublicProfileDTO
     */
    firstName?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoPublicProfileDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoPublicProfileDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPublicProfileDTO
     */
    profilePicUrl?: string;
}

/**
 * Check if a given object implements the DtoPublicProfileDTO interface.
 */
export function instanceOfDtoPublicProfileDTO(value: object): value is DtoPublicProfileDTO {
    return true;
}

export function DtoPublicProfileDTOFromJSON(json: any): DtoPublicProfileDTO {
    return DtoPublicProfileDTOFromJSONTyped(json, false);
}

export function DtoPublicProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoPublicProfileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'profilePicUrl': json['profilePicUrl'] == null ? undefined : json['profilePicUrl'],
    };
}

export function DtoPublicProfileDTOToJSON(json: any): DtoPublicProfileDTO {
    return DtoPublicProfileDTOToJSONTyped(json, false);
}

export function DtoPublicProfileDTOToJSONTyped(value?: DtoPublicProfileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'firstName': value['firstName'],
        'id': value['id'],
        'lastName': value['lastName'],
        'profilePicUrl': value['profilePicUrl'],
    };
}

