/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoSubscribeResponse
 */
export interface DtoSubscribeResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the DtoSubscribeResponse interface.
 */
export function instanceOfDtoSubscribeResponse(value: object): value is DtoSubscribeResponse {
    return true;
}

export function DtoSubscribeResponseFromJSON(json: any): DtoSubscribeResponse {
    return DtoSubscribeResponseFromJSONTyped(json, false);
}

export function DtoSubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoSubscribeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DtoSubscribeResponseToJSON(json: any): DtoSubscribeResponse {
    return DtoSubscribeResponseToJSONTyped(json, false);
}

export function DtoSubscribeResponseToJSONTyped(value?: DtoSubscribeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

