/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoSubscribeRequest
 */
export interface DtoSubscribeRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    lastContactPage?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscribeRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the DtoSubscribeRequest interface.
 */
export function instanceOfDtoSubscribeRequest(value: object): value is DtoSubscribeRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function DtoSubscribeRequestFromJSON(json: any): DtoSubscribeRequest {
    return DtoSubscribeRequestFromJSONTyped(json, false);
}

export function DtoSubscribeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoSubscribeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'email': json['email'],
        'language': json['language'] == null ? undefined : json['language'],
        'lastContactPage': json['lastContactPage'] == null ? undefined : json['lastContactPage'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function DtoSubscribeRequestToJSON(json: any): DtoSubscribeRequest {
    return DtoSubscribeRequestToJSONTyped(json, false);
}

export function DtoSubscribeRequestToJSONTyped(value?: DtoSubscribeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'email': value['email'],
        'language': value['language'],
        'lastContactPage': value['lastContactPage'],
        'timezone': value['timezone'],
    };
}

