/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoUpdatePageMetadataRequest
 */
export interface DtoUpdatePageMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoUpdatePageMetadataRequest
     */
    newUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdatePageMetadataRequest
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdatePageMetadataRequest
     */
    url: string;
}

/**
 * Check if a given object implements the DtoUpdatePageMetadataRequest interface.
 */
export function instanceOfDtoUpdatePageMetadataRequest(value: object): value is DtoUpdatePageMetadataRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DtoUpdatePageMetadataRequestFromJSON(json: any): DtoUpdatePageMetadataRequest {
    return DtoUpdatePageMetadataRequestFromJSONTyped(json, false);
}

export function DtoUpdatePageMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoUpdatePageMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newUrl': json['newUrl'] == null ? undefined : json['newUrl'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'url': json['url'],
    };
}

export function DtoUpdatePageMetadataRequestToJSON(json: any): DtoUpdatePageMetadataRequest {
    return DtoUpdatePageMetadataRequestToJSONTyped(json, false);
}

export function DtoUpdatePageMetadataRequestToJSONTyped(value?: DtoUpdatePageMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newUrl': value['newUrl'],
        'tags': value['tags'],
        'url': value['url'],
    };
}

