/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoUserDTO
 */
export interface DtoUserDTO {
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    firstName?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoUserDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    profilePicUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUserDTO
     */
    role?: string;
}

/**
 * Check if a given object implements the DtoUserDTO interface.
 */
export function instanceOfDtoUserDTO(value: object): value is DtoUserDTO {
    return true;
}

export function DtoUserDTOFromJSON(json: any): DtoUserDTO {
    return DtoUserDTOFromJSONTyped(json, false);
}

export function DtoUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'profilePicUrl': json['profilePicUrl'] == null ? undefined : json['profilePicUrl'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function DtoUserDTOToJSON(json: any): DtoUserDTO {
    return DtoUserDTOToJSONTyped(json, false);
}

export function DtoUserDTOToJSONTyped(value?: DtoUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'createdAt': value['createdAt'],
        'email': value['email'],
        'firstName': value['firstName'],
        'id': value['id'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'profilePicUrl': value['profilePicUrl'],
        'role': value['role'],
    };
}

