/* tslint:disable */
/* eslint-disable */
/**
 * PhotoTours API
 * API for PhotoTours platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoUpdateTourRequest
 */
export interface DtoUpdateTourRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoUpdateTourRequest
     */
    availableMonths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    difficulty?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    durationDays?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    endLocation?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DtoUpdateTourRequest
     */
    isShowRooms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DtoUpdateTourRequest
     */
    isShowVip?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoUpdateTourRequest
     */
    languages?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DtoUpdateTourRequest
     */
    minAge?: number;
    /**
     * 
     * @type {object}
     * @memberof DtoUpdateTourRequest
     */
    program?: object;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    reviewsSectionName?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoUpdateTourRequest
     */
    roomPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    startLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateTourRequest
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoUpdateTourRequest
     */
    vipPrice?: number;
}

/**
 * Check if a given object implements the DtoUpdateTourRequest interface.
 */
export function instanceOfDtoUpdateTourRequest(value: object): value is DtoUpdateTourRequest {
    return true;
}

export function DtoUpdateTourRequestFromJSON(json: any): DtoUpdateTourRequest {
    return DtoUpdateTourRequestFromJSONTyped(json, false);
}

export function DtoUpdateTourRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoUpdateTourRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMonths': json['availableMonths'] == null ? undefined : json['availableMonths'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'endLocation': json['endLocation'] == null ? undefined : json['endLocation'],
        'isShowRooms': json['isShowRooms'] == null ? undefined : json['isShowRooms'],
        'isShowVip': json['isShowVip'] == null ? undefined : json['isShowVip'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'program': json['program'] == null ? undefined : json['program'],
        'reviewsSectionName': json['reviewsSectionName'] == null ? undefined : json['reviewsSectionName'],
        'roomPrice': json['roomPrice'] == null ? undefined : json['roomPrice'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'title': json['title'] == null ? undefined : json['title'],
        'vipPrice': json['vipPrice'] == null ? undefined : json['vipPrice'],
    };
}

export function DtoUpdateTourRequestToJSON(json: any): DtoUpdateTourRequest {
    return DtoUpdateTourRequestToJSONTyped(json, false);
}

export function DtoUpdateTourRequestToJSONTyped(value?: DtoUpdateTourRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMonths': value['availableMonths'],
        'coverUrl': value['coverUrl'],
        'description': value['description'],
        'difficulty': value['difficulty'],
        'durationDays': value['durationDays'],
        'endLocation': value['endLocation'],
        'isShowRooms': value['isShowRooms'],
        'isShowVip': value['isShowVip'],
        'languages': value['languages'],
        'minAge': value['minAge'],
        'program': value['program'],
        'reviewsSectionName': value['reviewsSectionName'],
        'roomPrice': value['roomPrice'],
        'slug': value['slug'],
        'startLocation': value['startLocation'],
        'title': value['title'],
        'vipPrice': value['vipPrice'],
    };
}

