/* eslint-disable max-len */
const first = "/images/1.avif";
const second = "/images/2.avif";
const third = "/images/3.avif";
const fourth = "/images/4.avif";
const fifth = "/images/5.avif";
const sixth = "/images/6.avif";
import {Difficulty, type TourView} from "src/types/tour";

export const mockTours: TourView[] = [
  {
    id: 1,
    slug: "dubai-photography-workshop",
    title: "Dubai Photography Workshop",
    description:
      "Explore the UAE through your lens with this intensive photography workshop. Urban skylines and desert landscapes with pro guides.",
    difficulty: Difficulty.EASY,
    price: 1950,
    languages: ["English"],
    durationDays: 4,
    startLocation: "Dubai",
    endLocation: "Abu Dhabi",
    availableMonths: ["January"],
    coverUrl: first,
    photos: [first, second, third],
    dates: ["2025-10-01", "2025-11-15"],
    included: [
      "All transfers",
      "English-speaking photography guides",
      "Hotels (twin rooms; single +$1000)",
      "Breakfasts",
    ],
    activities: ["Sightseeing", "Photo Tours", "Photo Workshop"],
    dailyItinerary: [
      {day: 1, title: "Arrival", description: "Check-in and city walk.", photos: [fifth]},
      {day: 2, title: "Desert", description: "Sunrise dunes & night cityscape.", photos: [third]},
    ],
    tags: ["popular", "winter"],
    categories: ["workshop"],
    guide: {id: 7, name: "John Doe"},
  },
  {
    id: 2,
    title: "Iceland Aurora Hunt",
    description: "Chasing Northern Lights with pro guides.",
    difficulty: Difficulty.PRO,
    price: 2490,
    durationDays: 5,
    coverUrl: second,
    photos: [fourth, third],
    dates: ["2025-12-10", "2026-01-15"],
    activities: ["Photo Tours"],
    included: ["Transport", "Guides"],
  },
  {
    id: 3,
    slug: "dubai-photography-workshop",
    title: "Dubai Photography Workshop",
    description:
      "Explore the UAE through your lens with this intensive photography workshop. Urban skylines and desert landscapes with pro guides.",
    difficulty: Difficulty.EASY,
    price: 1950,
    languages: ["English"],
    durationDays: 4,
    startLocation: "Dubai",
    endLocation: "Abu Dhabi",
    availableMonths: ["January"],
    coverUrl: third,
    photos: [fourth, second, first],
    dates: ["2025-10-01", "2025-11-15"],
    included: [
      "All transfers",
      "English-speaking photography guides",
      "Hotels (twin rooms; single +$1000)",
      "Breakfasts",
    ],
    activities: ["Sightseeing", "Photo Tours", "Photo Workshop"],
    dailyItinerary: [
      {day: 1, title: "Arrival", description: "Check-in and city walk.", photos: [fourth]},
      {day: 2, title: "Desert", description: "Sunrise dunes & night cityscape.", photos: [second]},
    ],
    tags: ["popular", "winter"],
    categories: ["workshop"],
    guide: {id: 7, name: "John Doe"},
  },
  {
    id: 4,
    title: "Iceland Aurora Hunt",
    description: "Chasing Northern Lights with pro guides.",
    difficulty: Difficulty.EXPERIENCED,
    price: 2490,
    durationDays: 5,
    coverUrl: fourth,
    photos: [third, fifth],
    dates: ["2025-12-10", "2026-01-15"],
    activities: ["Photo Tours"],
    included: ["Transport", "Guides"],
  },
  {
    id: 5,
    slug: "dubai-photography-workshop",
    title: "Dubai Photography Workshop",
    description:
      "Explore the UAE through your lens with this intensive photography workshop. Urban skylines and desert landscapes with pro guides.",
    difficulty: Difficulty.EASY,
    price: 1950,
    languages: ["English"],
    durationDays: 4,
    startLocation: "Dubai",
    endLocation: "Abu Dhabi",
    availableMonths: ["January"],
    coverUrl: fifth,
    photos: [first, fifth, third],
    dates: ["2025-10-01", "2025-11-15"],
    included: [
      "All transfers",
      "English‑speaking photography guides",
      "Hotels (twin rooms; single +$1000)",
      "Breakfasts",
    ],
    activities: ["Sightseeing", "Photo Tours", "Photo Workshop"],
    dailyItinerary: [
      {day: 1, title: "Arrival", description: "Check‑in and city walk.", photos: [second]},
      {day: 2, title: "Desert", description: "Sunrise dunes & night cityscape.", photos: [third]},
    ],
    tags: ["popular", "winter"],
    categories: ["workshop"],
    guide: {id: 7, name: "John Doe"},
  },
  {
    id: 6,
    title: "Iceland Aurora Hunt",
    description: "Chasing Northern Lights with pro guides.",
    difficulty: Difficulty.EXPERIENCED,
    price: 2490,
    durationDays: 5,
    coverUrl: sixth,
    photos: [fourth, third],
    dates: ["2025-12-10", "2026-01-15"],
    activities: ["Photo Tours"],
    included: ["Transport", "Guides"],
  },
];

