{
 "title": "PT – Main Dashboard",
 "time": { "from": "2025-07-01T00:00:00.000Z", "to": "2025-08-02T00:00:00.000Z" },
 "panels": [
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS alive;\r\n" }
   ]
  },
  {
   "title": "User Registrations by Day ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', \"createdAt\") AS \"time\",\r\n  COUNT(*) AS value\r\nFROM \"User\"\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Users by Role",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  role,\r\n  COUNT(*) AS count\r\nFROM \"User\"\r\nGROUP BY role;\r\n\r\n"
    }
   ]
  },
  {
   "title": " Repeat Order Share",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH orders AS (\r\n  SELECT\r\n    \"userId\",\r\n    ROW_NUMBER() OVER (PARTITION BY \"userId\" ORDER BY \"createdAt\") AS rn\r\n  FROM \"Booking\"\r\n  WHERE status IN ('CONFIRMED','WAITING_LIST','PENDING')\r\n)\r\nSELECT\r\n  COUNT(*) FILTER (WHERE rn >= 2) ::decimal\r\n  / NULLIF(COUNT(*), 0) AS repeat_order_share\r\nFROM orders;\r\n"
    }
   ]
  },
  {
   "title": "Cohorts",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH cohorts AS (\r\n  SELECT\r\n    id AS user_id,\r\n    date_trunc('month', \"createdAt\") AS cohort_month\r\n  FROM \"User\"\r\n  WHERE role = 'CLIENT'\r\n)\r\nSELECT\r\n  c.cohort_month,\r\n  date_trunc('month', b.\"createdAt\") AS activity_month,\r\n  COUNT(DISTINCT b.\"userId\") AS active_users\r\nFROM cohorts c\r\nJOIN \"Booking\" b ON b.\"userId\" = c.user_id\r\nGROUP BY c.cohort_month, activity_month\r\nORDER BY c.cohort_month, activity_month;\r\n"
    }
   ]
  },
  {
   "title": "Tours by Popularity",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  t.id AS \"tourId\",\r\n  t.title,\r\n  COUNT(b.id) AS booking_count\r\nFROM \"Tour\" t\r\nLEFT JOIN \"Booking\" b ON b.\"tourId\" = t.id\r\nGROUP BY t.id, t.title\r\nORDER BY booking_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Unique Buyers by Day",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', \"createdAt\") AS \"time\",\r\n  COUNT(DISTINCT \"userId\") AS unique_buyers\r\nFROM \"Booking\"\r\nWHERE status IN ('CONFIRMED','WAITING_LIST','PENDING')\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": " Average Time to First Booking ",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  u.id AS \"userId\",\r\n  MIN(b.\"createdAt\") - u.\"createdAt\" AS \"time_to_first_booking\"\r\nFROM \"User\" u\r\nJOIN \"Booking\" b ON b.\"userId\" = u.id\r\nGROUP BY u.id;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Booking Status Distribution",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(*) AS count\r\nFROM \"Booking\"\r\nGROUP BY status;\r\n"
    }
   ]
  },
  {
   "title": "Revenue by Day",
   "type": "barchart",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', \"createdAt\") AS \"time\",\r\n  SUM(\"totalPrice\") AS \"revenue\"\r\nFROM \"Booking\"\r\nWHERE status = 'CONFIRMED'\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Average Booking Value",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(AVG(\"totalPrice\")) AS avg_booking_value\r\nFROM \"Booking\"\r\nWHERE status = 'CONFIRMED';\r\n"
    }
   ]
  },
  {
   "title": "Repeat Clients",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"userId\",\r\n  COUNT(*) AS bookings\r\nFROM \"Booking\"\r\nGROUP BY \"userId\"\r\nHAVING COUNT(*) > 1;\r\n"
    }
   ]
  },
  {
   "title": "Booking by Day",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', \"createdAt\") AS \"time\",\r\n  COUNT(*) AS \"bookings\"\r\nFROM \"Booking\"\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Cancellations by Day",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', \"createdAt\") AS \"time\",\r\n  COUNT(*) AS \"cancelled\"\r\nFROM \"Booking\"\r\nWHERE status = 'CANCELLED'\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}